/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DropboxSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/sync-engine.ts
var import_obsidian2 = require("obsidian");

// src/dropbox-auth.ts
var import_obsidian = require("obsidian");
function generateCodeVerifier() {
  const charset = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~";
  const array = new Uint8Array(64);
  crypto.getRandomValues(array);
  return Array.from(array, (byte) => charset[byte % charset.length]).join("");
}
async function generateCodeChallenge(verifier) {
  const encoder = new TextEncoder();
  const data = encoder.encode(verifier);
  const digest = await crypto.subtle.digest("SHA-256", data);
  return btoa(String.fromCharCode(...new Uint8Array(digest))).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}
function loadToken(raw) {
  if (!raw || typeof raw !== "object")
    return null;
  const t = raw;
  if (typeof t.access_token !== "string" || typeof t.refresh_token !== "string" || typeof t.expires_at !== "number") {
    return null;
  }
  return {
    access_token: t.access_token,
    refresh_token: t.refresh_token,
    expires_at: t.expires_at,
    account_id: typeof t.account_id === "string" ? t.account_id : void 0
  };
}
function saveToken(token) {
  var _a;
  return {
    dropboxToken: {
      access_token: token.access_token,
      refresh_token: token.refresh_token,
      expires_at: token.expires_at,
      account_id: (_a = token.account_id) != null ? _a : void 0
    }
  };
}
function clearToken() {
  return { dropboxToken: null };
}
function isTokenExpired(token) {
  return Date.now() >= token.expires_at - 3e5;
}
function isTokenValid(token) {
  if (!token)
    return false;
  return !!token.access_token && !!token.refresh_token;
}
var REDIRECT_PORT = 54219;
var REDIRECT_URI = `http://127.0.0.1:${REDIRECT_PORT}/`;
async function authorize(config) {
  const verifier = generateCodeVerifier();
  const challenge = await generateCodeChallenge(verifier);
  const state = generateCodeVerifier();
  let serverResult = null;
  try {
    console.log("Dropbox Sync: \u5C1D\u8BD5\u542F\u52A8\u672C\u5730 HTTP \u670D\u52A1\u5668...");
    serverResult = await startHttpServer();
    console.log("Dropbox Sync: \u672C\u5730\u670D\u52A1\u5668\u5DF2\u542F\u52A8\uFF0C\u7AEF\u53E3", REDIRECT_PORT);
  } catch (err) {
    console.warn("Dropbox Sync: \u672C\u5730\u670D\u52A1\u5668\u542F\u52A8\u5931\u8D25\uFF0C\u5C06\u4F7F\u7528\u624B\u52A8\u6A21\u5F0F", err);
  }
  const scopes = "files.metadata.read files.content.read files.content.write";
  const authUrl = `https://www.dropbox.com/oauth2/authorize?client_id=${encodeURIComponent(config.clientId)}&response_type=code&redirect_uri=${encodeURIComponent(REDIRECT_URI)}&code_challenge=${encodeURIComponent(challenge)}&code_challenge_method=S256&state=${encodeURIComponent(state)}&token_access_type=offline&scope=${encodeURIComponent(scopes)}`;
  new import_obsidian.Notice("\u6B63\u5728\u6253\u5F00\u6D4F\u89C8\u5668\u8FDB\u884C Dropbox \u6388\u6743\u2026");
  openUrl(authUrl);
  let code;
  if (serverResult) {
    console.log("Dropbox Sync: \u7B49\u5F85\u672C\u5730\u56DE\u8C03...");
    const result = await serverResult.promise;
    if (result.state !== state) {
      throw new Error("State \u4E0D\u5339\u914D \u2014 \u53EF\u80FD\u662F CSRF \u653B\u51FB");
    }
    code = result.code;
    console.log("Dropbox Sync: \u901A\u8FC7\u672C\u5730\u670D\u52A1\u5668\u6536\u5230\u6388\u6743\u7801");
  } else {
    code = await promptForCode(state);
  }
  return await exchangeCodeForToken(config.clientId, REDIRECT_URI, verifier, code);
}
async function startHttpServer() {
  let resolveCode;
  let rejectCode;
  const codePromise = new Promise((res, rej) => {
    resolveCode = res;
    rejectCode = rej;
  });
  const http = require("http");
  const url_mod = require("url");
  console.log("Dropbox Sync: require('http') \u6210\u529F");
  const server = http.createServer((req, res) => {
    const parsed = url_mod.parse(req.url || "", true);
    const code = parsed.query.code;
    const state = parsed.query.state;
    console.log("Dropbox Sync: \u6536\u5230\u56DE\u8C03", req.url);
    if (code) {
      res.writeHead(200, { "Content-Type": "text/html; charset=utf-8" });
      res.end(`<html><body><h2>\u2713 \u6388\u6743\u6210\u529F\uFF01</h2><p>\u4F60\u53EF\u4EE5\u5173\u95ED\u6B64\u9875\u9762\u4E86\u3002</p></body></html>`);
      server.close();
      resolveCode({ code, state });
    } else {
      res.writeHead(400, { "Content-Type": "text/html; charset=utf-8" });
      res.end(`<html><body><h2>\u2717 \u6388\u6743\u5931\u8D25</h2><p>\u672A\u6536\u5230\u6388\u6743\u7801\u3002</p></body></html>`);
      server.close();
      rejectCode(new Error("\u672A\u6536\u5230\u6388\u6743\u7801"));
    }
  });
  await new Promise((resolve, reject) => {
    server.on("error", (err) => {
      console.error("Dropbox Sync: \u670D\u52A1\u5668\u9519\u8BEF", err);
      reject(err);
    });
    server.listen(REDIRECT_PORT, "127.0.0.1", () => {
      console.log("Dropbox Sync: \u670D\u52A1\u5668\u5DF2\u542F\u52A8", REDIRECT_PORT);
      resolve();
    });
  });
  return { promise: codePromise };
}
async function promptForCode(expectedState) {
  const message = "\u2705 Dropbox \u6388\u6743\u7A97\u53E3\u5DF2\u6253\u5F00\n\n1. \u5728\u6D4F\u89C8\u5668\u4E2D\u5B8C\u6210\u6388\u6743\n2. \u6388\u6743\u540E\u6D4F\u89C8\u5668\u4F1A\u8DF3\u8F6C\u5230 http://127.0.0.1:54219/ \uFF08\u9875\u9762\u65E0\u6CD5\u8BBF\u95EE\u662F\u6B63\u5E38\u7684\uFF09\n3. \u590D\u5236\u6D4F\u89C8\u5668\u5730\u5740\u680F\u7684\u5B8C\u6574\u7F51\u5740\n4. \u70B9\u51FB\u786E\u5B9A\uFF0C\u7C98\u8D34\u5230\u4E0B\u9762\u7684\u8F93\u5165\u6846\n\n\u5982\u8BEF\u5173\u4E86\u6D4F\u89C8\u5668\uFF0C\u70B9\u51FB\u300C\u53D6\u6D88\u300D\u540E\u91CD\u65B0\u6388\u6743\u3002";
  const url = prompt(message);
  if (!url) {
    throw new Error("\u7528\u6237\u53D6\u6D88\u4E86\u6388\u6743");
  }
  try {
    const parsed = new URL(url);
    const code = parsed.searchParams.get("code");
    const state = parsed.searchParams.get("state");
    if (!code) {
      throw new Error("\u7F51\u5740\u4E2D\u672A\u627E\u5230\u6388\u6743\u7801 (code)\uFF0C\u8BF7\u786E\u8BA4\u590D\u5236\u7684\u662F\u5B8C\u6574\u5730\u5740\u680F\u5185\u5BB9");
    }
    if (state !== expectedState) {
      throw new Error("State \u4E0D\u5339\u914D \u2014 \u53EF\u80FD\u662F CSRF \u653B\u51FB\uFF0C\u8BF7\u91CD\u65B0\u6388\u6743");
    }
    return code;
  } catch (err) {
    if (err instanceof TypeError && err.message.includes("URL")) {
      throw new Error("\u7F51\u5740\u683C\u5F0F\u4E0D\u6B63\u786E\uFF0C\u8BF7\u590D\u5236\u6D4F\u89C8\u5668\u5730\u5740\u680F\u6574\u6BB5\u5185\u5BB9");
    }
    throw err;
  }
}
async function exchangeCodeForToken(clientId, redirectUri, codeVerifier, code) {
  var _a, _b;
  const body = new URLSearchParams({
    code,
    grant_type: "authorization_code",
    client_id: clientId,
    redirect_uri: redirectUri,
    code_verifier: codeVerifier
  });
  const response = await (0, import_obsidian.requestUrl)({
    url: "https://api.dropboxapi.com/oauth2/token",
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: body.toString()
  });
  if (response.status !== 200) {
    const err = JSON.parse(response.text);
    throw new Error(`Dropbox \u6388\u6743\u9519\u8BEF\uFF1A${err.error} \u2014 ${(_a = err.error_description) != null ? _a : ""}`);
  }
  const data = JSON.parse(response.text);
  return {
    access_token: data.access_token,
    refresh_token: (_b = data.refresh_token) != null ? _b : "",
    expires_at: Date.now() + data.expires_in * 1e3,
    account_id: data.account_id
  };
}
async function refreshToken(clientId, token) {
  var _a, _b, _c;
  if (!token.refresh_token) {
    throw new Error("\u6CA1\u6709 refresh token \u2014 \u8BF7\u91CD\u65B0\u6388\u6743");
  }
  const body = new URLSearchParams({
    refresh_token: token.refresh_token,
    grant_type: "refresh_token",
    client_id: clientId
  });
  const response = await (0, import_obsidian.requestUrl)({
    url: "https://api.dropboxapi.com/oauth2/token",
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: body.toString()
  });
  if (response.status !== 200) {
    const err = JSON.parse(response.text);
    throw new Error(`\u5237\u65B0 token \u5931\u8D25\uFF1A${err.error} \u2014 ${(_a = err.error_description) != null ? _a : ""}`);
  }
  const data = JSON.parse(response.text);
  return {
    access_token: data.access_token,
    refresh_token: (_b = data.refresh_token) != null ? _b : token.refresh_token,
    expires_at: Date.now() + data.expires_in * 1e3,
    account_id: (_c = data.account_id) != null ? _c : token.account_id
  };
}
function openUrl(url) {
  if (import_obsidian.Platform.isDesktop) {
    const { shell } = require("electron");
    shell.openExternal(url);
  } else {
    window.open(url, "_blank");
  }
}

// src/sync-engine.ts
var MAX_LOG_LINES = 500;
var _logBuffer = [];
function addLog(msg) {
  const entry = `[${(/* @__PURE__ */ new Date()).toLocaleTimeString()}] ${msg}`;
  _logBuffer.push(entry);
  if (_logBuffer.length > MAX_LOG_LINES)
    _logBuffer.shift();
  console.log("Dropbox Sync:", msg);
}
function getLogs() {
  return [..._logBuffer];
}
function clearLogs() {
  _logBuffer.length = 0;
}
var REMOTE_STATE_FILENAME = ".sync_state.json";
var SyncEngine = class {
  constructor(vault, token, options) {
    this.abortController = null;
    this.vault = vault;
    this.token = token;
    this.options = {
      ...options,
      remoteBasePath: "/" + options.remoteBasePath.replace(/^\/+|\/+$/g, "")
    };
    this.status = {
      running: false,
      lastSyncAt: null,
      lastError: null,
      progress: { total: 0, completed: 0, current: "" }
    };
    addLog("SyncEngine \u521B\u5EFA: " + JSON.stringify({
      direction: options.direction,
      remoteBasePath: this.options.remoteBasePath
    }));
  }
  getStatus() {
    return { ...this.status, progress: { ...this.status.progress } };
  }
  isRunning() {
    return this.status.running;
  }
  updateToken(token) {
    this.token = token;
  }
  getOptions() {
    return { ...this.options };
  }
  // ─── 全量同步 ──────────────────────────────────────────────────────────
  async syncNow() {
    if (this.status.running) {
      console.warn("Dropbox Sync: \u540C\u6B65\u5DF2\u5728\u8FDB\u884C\u4E2D");
      throw new Error("\u540C\u6B65\u5DF2\u5728\u8FDB\u884C\u4E2D");
    }
    this.abortController = new AbortController();
    this.status.running = true;
    this.status.lastError = null;
    this.status.progress = { total: 0, completed: 0, current: "\u6B63\u5728\u542F\u52A8\u2026" };
    addLog("=== \u5F00\u59CB\u540C\u6B65 ===");
    addLog(`\u65B9\u5411: ${this.options.direction}`);
    try {
      await this.ensureValidToken();
      const result = await this.runSync();
      this.status.lastSyncAt = Date.now();
      addLog("=== \u540C\u6B65\u5B8C\u6210 ===");
      new import_obsidian2.Notice("Dropbox \u540C\u6B65\u5B8C\u6210");
      return result;
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      this.status.lastError = msg;
      console.error("Dropbox Sync: === \u540C\u6B65\u5931\u8D25 ===", err);
      new import_obsidian2.Notice(`Dropbox \u540C\u6B65\u9519\u8BEF\uFF1A${msg}`, 8e3);
      throw err;
    } finally {
      this.status.running = false;
      this.abortController = null;
    }
  }
  cancel() {
    addLog("\u7528\u6237\u53D6\u6D88\u4E86\u540C\u6B65");
    if (this.abortController) {
      this.abortController.abort();
    }
    this.status.running = false;
  }
  /**
   * 首次同步 / 强制重扫：清空本地状态 + 删除远程状态文件 → 全量同步
   */
  async syncFresh() {
    addLog("=== \u9996\u6B21\u540C\u6B65 / \u5F3A\u5236\u91CD\u626B ===");
    await this.saveLocalState({ files: {} });
    addLog("\u672C\u5730\u72B6\u6001\u5DF2\u6E05\u7A7A");
    try {
      await this.ensureValidToken();
      await this.dropboxDelete(this.remoteStatePath());
      addLog("\u8FDC\u7A0B\u72B6\u6001\u6587\u4EF6\u5DF2\u5220\u9664");
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      if (!msg.includes("not_found")) {
        console.warn("Dropbox Sync: \u5220\u9664\u8FDC\u7A0B\u72B6\u6001\u6587\u4EF6\u5931\u8D25", msg);
      }
    }
    return await this.syncNow();
  }
  // ─── 单文件保存同步 ──────────────────────────────────────────────────
  async uploadFile(file) {
    if (this.status.running) {
      addLog(`\u5168\u91CF\u540C\u6B65\u4E2D\uFF0C\u8DF3\u8FC7\u4FDD\u5B58\u65F6\u4E0A\u4F20 ${file.path}`);
      return;
    }
    try {
      await this.ensureValidToken();
      const localPath = file.path;
      const remotePath = this.localToRemote(localPath);
      const content = await this.vault.readBinary(file);
      if (this.options.maxFileSize > 0 && content.byteLength > this.options.maxFileSize) {
        addLog(`\u6587\u4EF6\u8D85\u8FC7\u5927\u5C0F\u9650\u5236 ${localPath}`);
        return;
      }
      addLog(`\u4FDD\u5B58\u65F6\u4E0A\u4F20 ${localPath}`);
      await this.dropboxUpload(remotePath, content);
    } catch (err) {
      console.error(`Dropbox Sync: \u4FDD\u5B58\u65F6\u4E0A\u4F20\u5931\u8D25 ${file.path}:`, err);
    }
  }
  shouldSync(file) {
    if (file instanceof import_obsidian2.TFolder)
      return false;
    const p = file.path;
    if (this.options.localPrefix && !p.startsWith(this.options.localPrefix))
      return false;
    const basename = file.name;
    if (basename.startsWith("."))
      return false;
    if (basename === "desktop.ini")
      return false;
    if (p.startsWith(".obsidian/"))
      return false;
    if (p === ".obsidian")
      return false;
    if (basename.includes(".conflict."))
      return false;
    if (basename === "state.json" && p.endsWith("/state.json"))
      return false;
    return true;
  }
  // ─── 内部同步逻辑（状态文件驱动） ───────────────────────────────────────
  async runSync() {
    var _a;
    await this.createRemoteFolder();
    const localState = await this.loadLocalState();
    addLog("\u672C\u5730\u72B6\u6001\u6587\u4EF6\u5DF2\u52A0\u8F7D");
    addLog("\u5F00\u59CB\u626B\u63CF\u672C\u5730\u6587\u4EF6\uFF0C\u8BA1\u7B97 SHA-256 \u54C8\u5E0C\u2026");
    this.status.progress.current = "\u6B63\u5728\u626B\u63CF\u672C\u5730\u6587\u4EF6\u2026";
    const newLocalState = await this.detectLocalChanges(localState);
    addLog("\u626B\u63CF\u5B8C\u6210");
    addLog("\u672C\u5730\u6587\u4EF6\u6570: " + Object.keys(newLocalState.files).length);
    this.status.progress.current = "\u6B63\u5728\u4E0B\u8F7D\u8FDC\u7A0B\u72B6\u6001\u2026";
    addLog("\u4E0B\u8F7D\u8FDC\u7A0B\u72B6\u6001\u2026");
    let remoteState = await this.downloadRemoteState();
    addLog("\u8FDC\u7A0B\u72B6\u6001\u4E0B\u8F7D\u5B8C\u6210");
    if (!remoteState.files || Object.keys(remoteState.files).length === 0) {
      addLog("\u8FDC\u7A0B\u65E0\u72B6\u6001\u6587\u4EF6\uFF0C\u626B\u63CF\u8FDC\u7A0B\u76EE\u5F55\u2026");
      remoteState = await this.listRemoteFilesToState();
      if (remoteState.files && Object.keys(remoteState.files).length > 0) {
        const remoteOnly = Object.keys(remoteState.files).filter(
          (p) => !(p in (newLocalState.files || {}))
        );
        addLog(`\u53D1\u73B0 ${Object.keys(remoteState.files).length} \u4E2A\u8FDC\u7A0B\u6587\u4EF6\uFF08${remoteOnly.length} \u4E2A\u4EC5\u8FDC\u7A0B\uFF09`);
      } else {
        addLog("\u8FDC\u7A0B\u76EE\u5F55\u4E3A\u7A7A\uFF08\u5168\u65B0\u5F00\u59CB\uFF09");
      }
    } else {
      addLog(`\u8FDC\u7A0B\u72B6\u6001\u5305\u542B ${Object.keys(remoteState.files).length} \u4E2A\u6587\u4EF6`);
    }
    const beforeFilterCount = Object.keys(remoteState.files || {}).length;
    remoteState = this.filterStatePaths(remoteState);
    const filteredCount = beforeFilterCount - Object.keys(remoteState.files || {}).length;
    if (filteredCount > 0) {
      addLog(`\u8FDC\u7A0B\u72B6\u6001\u8FC7\u6EE4\u4E86 ${filteredCount} \u4E2A\u4E0D\u5E94\u540C\u6B65\u7684\u6761\u76EE`);
    }
    const actions = this.resolveStateActions(newLocalState, remoteState, this.options.direction);
    addLog(`\u5F85\u5904\u7406 ${actions.length} \u4E2A\u6587\u4EF6`);
    if (actions.length > 0) {
      addLog(`\u64CD\u4F5C: ${actions.map((a) => `${a.action}:${a.path}`).join(", ")}`);
    }
    this.status.progress.total = actions.length;
    this.status.progress.completed = 0;
    for (const action of actions) {
      if ((_a = this.abortController) == null ? void 0 : _a.signal.aborted) {
        throw new Error("\u540C\u6B65\u5DF2\u53D6\u6D88");
      }
      this.status.progress.current = action.path;
      try {
        await this.executeAction(action, newLocalState, remoteState);
        await this.saveLocalState(this.mergeStates(newLocalState, remoteState));
        addLog(`[${this.status.progress.completed + 1}/${actions.length}] ${action.action} ${action.path}`);
      } catch (err) {
        console.error(`Dropbox Sync: \u64CD\u4F5C\u5931\u8D25 ${action.action} ${action.path}:`, err);
      }
      this.status.progress.completed++;
    }
    const merged = this.mergeStates(newLocalState, remoteState);
    await this.saveLocalState(merged);
    addLog("\u672C\u5730\u72B6\u6001\u5DF2\u4FDD\u5B58");
    try {
      await this.uploadRemoteState(merged);
      addLog("\u8FDC\u7A0B\u72B6\u6001\u5DF2\u4E0A\u4F20");
    } catch (err) {
      console.error("Dropbox Sync: \u8FDC\u7A0B\u72B6\u6001\u4E0A\u4F20\u5931\u8D25\uFF08\u975E\u81F4\u547D\uFF09", err);
    }
    return { lastSyncAt: Date.now(), actionsCompleted: actions.length };
  }
  // ─── Hash ──────────────────────────────────────────────────────────────────
  async fileHash(content) {
    const hash = await crypto.subtle.digest("SHA-256", content);
    return Array.from(new Uint8Array(hash)).map((b) => b.toString(16).padStart(2, "0")).join("");
  }
  // ─── 本地状态文件管理 ─────────────────────────────────────────────────
  async loadLocalState() {
    const _fs = getFs();
    if (_fs) {
      try {
        const content = _fs.readFileSync(this.options.stateFilePath, "utf-8");
        return JSON.parse(content);
      } catch (err) {
        if (err instanceof Error && err.code !== "ENOENT") {
          console.warn("Dropbox Sync: \u8BFB\u53D6\u672C\u5730\u72B6\u6001\u6587\u4EF6\u5931\u8D25", this.options.stateFilePath, err);
        }
        return { files: {} };
      }
    }
    try {
      const adapter = this.vault.adapter;
      const vaultPath = `.obsidian/plugins/obsidian-dropbox-sync/state.json`;
      const content = await adapter.read(vaultPath);
      return JSON.parse(content);
    } catch (e) {
      return { files: {} };
    }
  }
  async saveLocalState(state) {
    const _fs = getFs();
    if (_fs) {
      try {
        _fs.writeFileSync(this.options.stateFilePath, JSON.stringify(state, null, 2), "utf-8");
        return;
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        console.error("Dropbox Sync: \u4FDD\u5B58\u672C\u5730\u72B6\u6001\u6587\u4EF6\u5931\u8D25", this.options.stateFilePath, msg);
        throw new Error(`\u65E0\u6CD5\u5199\u5165\u72B6\u6001\u6587\u4EF6 ${this.options.stateFilePath}: ${msg}`);
      }
    }
    try {
      const adapter = this.vault.adapter;
      const vaultPath = `.obsidian/plugins/obsidian-dropbox-sync/state.json`;
      await adapter.write(vaultPath, JSON.stringify(state, null, 2));
    } catch (err) {
      console.warn("Dropbox Sync: \u4FDD\u5B58\u72B6\u6001\u5230 vault \u5931\u8D25", err);
    }
  }
  // ─── 远程状态文件管理 ────────────────────────────────────────────────
  remoteStatePath() {
    const base = this.options.remoteBasePath.replace(/\/+$/, "");
    return `${base}/${REMOTE_STATE_FILENAME}`;
  }
  async downloadRemoteState() {
    try {
      const content = await this.dropboxDownload(this.remoteStatePath());
      const text = new TextDecoder().decode(content);
      return JSON.parse(text);
    } catch (e) {
      return { files: {} };
    }
  }
  async uploadRemoteState(state) {
    const json = JSON.stringify(state, null, 2);
    const encoded = new TextEncoder().encode(json);
    const content = encoded.buffer.slice(encoded.byteOffset, encoded.byteOffset + encoded.byteLength);
    try {
      await this.dropboxUpload(this.remoteStatePath(), content);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      if (msg.includes("not_found")) {
        await this.createRemoteFolder();
        await this.dropboxUpload(this.remoteStatePath(), content);
      } else {
        throw err;
      }
    }
  }
  async listRemoteFilesToState() {
    const state = { files: {} };
    try {
      let result = await this.dropboxListFolder(this.options.remoteBasePath);
      let entries = result.entries;
      let cursor = result.cursor;
      let hasMore = result.has_more;
      while (hasMore) {
        result = await this.dropboxListFolderContinue(cursor);
        entries = entries.concat(result.entries);
        cursor = result.cursor;
        hasMore = result.has_more;
      }
      for (const entry of entries) {
        if (entry[".tag"] !== "file")
          continue;
        const rel = this.relativeRemotePath(entry.path_lower);
        if (rel === REMOTE_STATE_FILENAME)
          continue;
        state.files[rel] = { v: 1, exists: true, h: "" };
      }
    } catch (e) {
    }
    return state;
  }
  // ─── 本地文件扫描 + hash + 版本检测 ─────────────────────────────────
  async detectLocalChanges(oldState) {
    var _a;
    const oldFiles = oldState.files || {};
    const newFiles = {};
    const allFiles = this.vault.getFiles();
    for (const file of allFiles) {
      if (!this.shouldSync(file))
        continue;
      const relPath = this.relativePath(file.path);
      if (this.options.maxFileSize > 0 && file.stat.size > this.options.maxFileSize) {
        addLog(`\u8DF3\u8FC7\u8D85\u5927\u6587\u4EF6 ${relPath}`);
        continue;
      }
      let content;
      try {
        content = await this.vault.readBinary(file);
      } catch (err) {
        console.warn("Dropbox Sync: \u8BFB\u53D6\u6587\u4EF6\u5931\u8D25", relPath, err);
        continue;
      }
      const h = await this.fileHash(content);
      const oldEntry = oldFiles[relPath] || {};
      const oldV = oldEntry.v || 0;
      const oldHash = oldEntry.h || "";
      if (((_a = oldEntry.exists) != null ? _a : true) && h === oldHash) {
        newFiles[relPath] = { v: oldV, exists: true, h };
      } else {
        newFiles[relPath] = { v: oldV + 1, exists: true, h };
      }
    }
    for (const [p, entry] of Object.entries(oldFiles)) {
      if (!(p in newFiles)) {
        if (entry.exists) {
          newFiles[p] = { v: (entry.v || 0) + 1, exists: false, h: "" };
        } else {
          newFiles[p] = entry;
        }
      }
    }
    return { files: newFiles };
  }
  // ─── 过滤不应同步的路径 ──────────────────────────────────────────────
  filterStatePaths(state) {
    const filtered = {};
    for (const [relPath, entry] of Object.entries(state.files || {})) {
      const parts = relPath.split("/");
      const basename = parts.pop() || relPath;
      if (basename.startsWith("."))
        continue;
      if (parts.some((p) => p.startsWith(".")))
        continue;
      if (basename === "desktop.ini")
        continue;
      if (basename.includes(".conflict."))
        continue;
      if (basename === REMOTE_STATE_FILENAME)
        continue;
      filtered[relPath] = entry;
    }
    return { files: filtered };
  }
  // ─── 版本号对比 → 决议操作 ────────────────────────────────────────
  resolveStateActions(localState, remoteState, direction) {
    var _a, _b;
    const actions = [];
    const localFiles = localState.files || {};
    const remoteFiles = remoteState.files || {};
    const allPaths = /* @__PURE__ */ new Set([...Object.keys(localFiles), ...Object.keys(remoteFiles)]);
    const hashMatch = (le, re) => {
      const lh = le.h || "";
      const rh = re.h || "";
      return !!(lh && rh && lh === rh);
    };
    for (const path of allPaths) {
      const lEntry = localFiles[path] || {};
      const rEntry = remoteFiles[path] || {};
      const lv = lEntry.v || 0;
      const rv = rEntry.v || 0;
      const lExists = path in localFiles ? (_a = lEntry.exists) != null ? _a : true : false;
      const rExists = path in remoteFiles ? (_b = rEntry.exists) != null ? _b : true : false;
      if (direction === "upload") {
        if (lv > rv) {
          if (lExists && !hashMatch(lEntry, rEntry)) {
            actions.push({ path, action: "upload" });
          } else if (rExists && !lExists) {
            actions.push({ path, action: "delete" });
          }
        } else if (rv > lv && !(path in localFiles) && rExists) {
          actions.push({ path, action: "delete" });
        }
      } else if (direction === "download") {
        if (rv > lv) {
          if (rExists && !hashMatch(lEntry, rEntry)) {
            actions.push({ path, action: "download" });
          } else if (lExists && !rExists) {
            actions.push({ path, action: "delete_local" });
          }
        } else if (lv > rv && !(path in remoteFiles) && lExists) {
          actions.push({ path, action: "delete_local" });
        }
      } else {
        if (lv > rv) {
          if (lExists && !hashMatch(lEntry, rEntry)) {
            actions.push({ path, action: "upload" });
          } else if (rExists && !lExists) {
            actions.push({ path, action: "delete" });
          }
        } else if (rv > lv) {
          if (rExists && !hashMatch(lEntry, rEntry)) {
            actions.push({ path, action: "download" });
          } else if (lExists && !rExists) {
            actions.push({ path, action: "delete_local" });
          }
        }
      }
    }
    return actions;
  }
  // ─── 合并两端状态 ────────────────────────────────────────────────────
  mergeStates(localState, remoteState) {
    const merged = { files: {} };
    const allPaths = /* @__PURE__ */ new Set([
      ...Object.keys(localState.files || {}),
      ...Object.keys(remoteState.files || {})
    ]);
    for (const path of allPaths) {
      const lEntry = (localState.files || {})[path] || {};
      const rEntry = (remoteState.files || {})[path] || {};
      const lv = lEntry.v || 0;
      const rv = rEntry.v || 0;
      merged.files[path] = lv >= rv ? lEntry : rEntry;
    }
    return merged;
  }
  // ─── 执行单个操作 ───────────────────────────────────────────────────
  async executeAction(action, localState, remoteState) {
    var _a, _b, _c, _d;
    const localPath = this.remoteToLocal(action.path);
    const remotePath = this.localToRemote(localPath);
    if (action.action === "upload") {
      const file = this.vault.getFileByPath(localPath);
      if (!file) {
        console.warn("Dropbox Sync: \u4E0A\u4F20\u65F6\u6587\u4EF6\u6D88\u5931", localPath);
        return;
      }
      const content = await this.vault.readBinary(file);
      await this.dropboxUpload(remotePath, content);
      remoteState.files[action.path] = { ...localState.files[action.path] || { v: 1, exists: true, h: "" } };
    } else if (action.action === "download") {
      const content = await this.dropboxDownload(remotePath);
      const h = await this.fileHash(content);
      const parent = localPath.substring(0, localPath.lastIndexOf("/"));
      if (parent && !await this.vault.adapter.exists(parent)) {
        await this.vault.createFolder(parent);
      }
      const existing = this.vault.getFileByPath(localPath);
      if (existing) {
        await this.vault.modifyBinary(existing, content);
      } else {
        await this.vault.createBinary(localPath, content);
      }
      const rEntry = remoteState.files[action.path] || { v: 1, exists: true, h: "" };
      localState.files[action.path] = { ...rEntry, h };
    } else if (action.action === "delete") {
      try {
        await this.dropboxDelete(remotePath);
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        if (!msg.includes("not_found"))
          throw err;
      }
      const lv = ((_a = localState.files[action.path]) == null ? void 0 : _a.v) || 0;
      const rv = ((_b = remoteState.files[action.path]) == null ? void 0 : _b.v) || 0;
      const maxV = Math.max(lv, rv);
      remoteState.files[action.path] = { v: maxV, exists: false, h: "" };
      if (!(action.path in localState.files)) {
        localState.files[action.path] = { v: maxV, exists: false, h: "" };
      }
    } else if (action.action === "delete_local") {
      const file = this.vault.getFileByPath(localPath);
      if (file)
        await this.vault.delete(file, true);
      const lv = ((_c = localState.files[action.path]) == null ? void 0 : _c.v) || 0;
      const rv = ((_d = remoteState.files[action.path]) == null ? void 0 : _d.v) || 0;
      const maxV = Math.max(lv, rv);
      localState.files[action.path] = { v: maxV, exists: false, h: "" };
      if (!(action.path in remoteState.files)) {
        remoteState.files[action.path] = { v: maxV, exists: false, h: "" };
      }
    }
  }
  // ─── 路径工具 ──────────────────────────────────────────────────────────
  relativePath(absolutePath) {
    if (this.options.localPrefix) {
      if (absolutePath.startsWith(this.options.localPrefix + "/")) {
        return absolutePath.substring(this.options.localPrefix.length + 1);
      }
      if (absolutePath === this.options.localPrefix)
        return "";
    }
    return absolutePath;
  }
  localToRemote(localPath) {
    const base = this.options.remoteBasePath.replace(/\/+$/, "");
    return `${base}/${localPath}`;
  }
  remoteToLocal(remotePath) {
    const prefix = this.options.localPrefix || "";
    return prefix ? `${prefix}/${remotePath}` : remotePath;
  }
  relativeRemotePath(remoteLower) {
    const base = this.options.remoteBasePath.toLowerCase().replace(/\/+$/, "");
    if (remoteLower.startsWith(base + "/")) {
      return remoteLower.substring(base.length + 1);
    }
    return remoteLower;
  }
  // ─── Token ─────────────────────────────────────────────────────────────
  async ensureValidToken() {
    if (isTokenExpired(this.token)) {
      addLog("token \u8FC7\u671F\uFF0C\u5237\u65B0\u2026");
      this.token = await refreshToken(this.options.clientId, this.token);
      addLog("token \u5237\u65B0\u6210\u529F");
    }
  }
  // ─── Dropbox API ───────────────────────────────────────────────────────
  /**
   * JSON API 调用（带 401 自动刷新 + 409 自动建目录）
   */
  async apiCall(url, body) {
    var _a, _b, _c, _d;
    const attempt = async () => {
      const response = await (0, import_obsidian2.requestUrl)({
        url,
        method: "POST",
        headers: {
          "Authorization": `Bearer ${this.token.access_token}`,
          "Content-Type": "application/json"
        },
        body,
        throw: false
      });
      if (response.status === 401) {
        addLog("API \u8FD4\u56DE 401\uFF0C\u81EA\u52A8\u5237\u65B0 token \u540E\u91CD\u8BD5...");
        await this.ensureValidToken();
        const retry = await (0, import_obsidian2.requestUrl)({
          url,
          method: "POST",
          headers: {
            "Authorization": `Bearer ${this.token.access_token}`,
            "Content-Type": "application/json"
          },
          body,
          throw: false
        });
        return { status: retry.status, text: retry.text };
      }
      return { status: response.status, text: response.text };
    };
    const result = await attempt();
    if (result.status === 409) {
      try {
        const err = JSON.parse(result.text);
        if (((_a = err == null ? void 0 : err.error) == null ? void 0 : _a[".tag"]) === "path" && ((_c = (_b = err == null ? void 0 : err.error) == null ? void 0 : _b.path) == null ? void 0 : _c[".tag"]) === "not_found") {
          const parsed = JSON.parse(body);
          const parentPath = ((_d = parsed.path) == null ? void 0 : _d.split("/").slice(0, -1).join("/")) || "";
          if (parentPath) {
            addLog("\u76EE\u5F55\u4E0D\u5B58\u5728\uFF0C\u81EA\u52A8\u521B\u5EFA: " + parentPath);
            await this.createFolder(parentPath);
            const retry = await attempt();
            return retry;
          }
        }
      } catch (e) {
      }
    }
    if (result.status >= 400) {
      throw new Error(`Dropbox API \u9519\u8BEF (${result.status}): ${result.text}`);
    }
    return result;
  }
  /**
   * 二进制 API 调用（带 401 自动刷新）
   */
  async apiCallBinary(url, body, extraHeaders) {
    const attempt = async () => {
      const headers = { "Authorization": `Bearer ${this.token.access_token}`, ...extraHeaders };
      const response = await (0, import_obsidian2.requestUrl)({
        url,
        method: "POST",
        headers,
        body: body != null ? body : void 0,
        throw: false
      });
      if (response.status === 401) {
        addLog("\u4E8C\u8FDB\u5236 API \u8FD4\u56DE 401\uFF0C\u81EA\u52A8\u5237\u65B0 token \u540E\u91CD\u8BD5...");
        await this.ensureValidToken();
        const retryHeaders = { "Authorization": `Bearer ${this.token.access_token}`, ...extraHeaders };
        const retry = await (0, import_obsidian2.requestUrl)({
          url,
          method: "POST",
          headers: retryHeaders,
          body: body != null ? body : void 0,
          throw: false
        });
        return {
          arrayBuffer: () => Promise.resolve(retry.arrayBuffer),
          status: retry.status
        };
      }
      return {
        arrayBuffer: () => Promise.resolve(response.arrayBuffer),
        status: response.status
      };
    };
    const result = await attempt();
    if (result.status >= 400) {
      throw new Error(`Dropbox API \u9519\u8BEF (${result.status})`);
    }
    return result;
  }
  async dropboxListFolder(path, recursive = true) {
    const body = JSON.stringify({
      path,
      recursive,
      include_media_info: false,
      include_deleted: false,
      include_has_explicit_shared_members: false
    });
    const response = await this.apiCall("https://api.dropboxapi.com/2/files/list_folder", body);
    return JSON.parse(response.text);
  }
  async dropboxListFolderContinue(cursor) {
    const body = JSON.stringify({ cursor });
    const response = await this.apiCall("https://api.dropboxapi.com/2/files/list_folder/continue", body);
    return JSON.parse(response.text);
  }
  async dropboxUpload(remotePath, content) {
    const headers = {
      "Content-Type": "application/octet-stream",
      "Dropbox-API-Arg": JSON.stringify({
        path: remotePath,
        mode: "overwrite",
        autorename: false,
        mute: false
      })
    };
    await this.apiCallBinary("https://content.dropboxapi.com/2/files/upload", content, headers);
  }
  async dropboxDownload(remotePath) {
    const headers = {
      "Dropbox-API-Arg": JSON.stringify({ path: remotePath })
    };
    const response = await this.apiCallBinary(
      "https://content.dropboxapi.com/2/files/download",
      null,
      headers
    );
    return response.arrayBuffer();
  }
  async dropboxDelete(remotePath) {
    const body = JSON.stringify({ path: remotePath });
    await this.apiCall("https://api.dropboxapi.com/2/files/delete_v2", body);
  }
  async createFolder(dirPath) {
    const body = JSON.stringify({ path: dirPath, autorename: false });
    try {
      await this.apiCall("https://api.dropboxapi.com/2/files/create_folder_v2", body);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      if (!msg.includes("409") && !msg.includes("conflict"))
        throw err;
    }
  }
  async createRemoteFolder() {
    await this.createFolder(this.options.remoteBasePath);
  }
  // ─── 工具 ─────────────────────────────────────────────────────────────
  /** 在文件名中插入后缀（保留扩展名），如 note.md → note.suffix.md */
  insertSuffix(filePath, suffix) {
    const dot = filePath.lastIndexOf(".");
    if (dot === -1)
      return filePath + suffix;
    return filePath.slice(0, dot) + suffix + filePath.slice(dot);
  }
};
function getFs() {
  try {
    return require("fs");
  } catch (e) {
    return null;
  }
}

// src/settings.ts
var import_obsidian3 = require("obsidian");
var DEFAULT_SETTINGS = {
  clientId: "",
  dropboxToken: null,
  syncDirection: "upload",
  remotePath: "/Apps/ObsidianSync",
  localPrefix: "",
  maxFileSize: 50 * 1024 * 1024,
  // 50 MB
  syncOnSave: true,
  lastSyncAt: 0
};
var ExportModal = class extends import_obsidian3.Modal {
  constructor(app, jsonStr) {
    super(app);
    this.jsonStr = jsonStr;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "\u5BFC\u51FA\u914D\u7F6E" });
    contentEl.createEl("p", {
      text: "\u8BF7\u957F\u6309\u4E0B\u65B9\u6587\u672C\u5168\u9009\u540E\u590D\u5236\uFF0C\u7136\u540E\u53D1\u9001\u5230\u53E6\u4E00\u53F0\u8BBE\u5907"
    });
    const textarea = contentEl.createEl("textarea", {
      attr: {
        readonly: "readonly",
        rows: "16",
        style: "width: 100%; font-family: monospace; font-size: 13px; box-sizing: border-box; resize: vertical; user-select: all;"
      }
    });
    textarea.value = this.jsonStr;
    contentEl.createEl("br");
    const closeBtn = contentEl.createEl("button", {
      text: "\u5173\u95ED",
      attr: { style: "cursor: pointer;" }
    });
    closeBtn.addEventListener("click", () => this.close());
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ImportModal = class extends import_obsidian3.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "\u5BFC\u5165\u914D\u7F6E" });
    contentEl.createEl("p", {
      text: "\u8BF7\u7C98\u8D34\u4E4B\u524D\u5BFC\u51FA\u7684\u914D\u7F6E JSON\uFF08\u5305\u542B App Key\u3001Token \u7B49\u5168\u90E8\u8BBE\u7F6E\uFF09"
    });
    const textarea = contentEl.createEl("textarea", {
      attr: {
        rows: "12",
        style: "width: 100%; font-family: monospace; font-size: 13px; box-sizing: border-box; resize: vertical;",
        placeholder: "\u5728\u6B64\u7C98\u8D34\u914D\u7F6E JSON \u2026"
      }
    });
    const btnContainer = contentEl.createDiv({
      attr: { style: "display: flex; gap: 8px; margin-top: 12px;" }
    });
    const importBtn = btnContainer.createEl("button", {
      text: "\u{1F4E5} \u5BFC\u5165",
      attr: { style: "flex: 1; cursor: pointer;" }
    });
    importBtn.addEventListener("click", async () => {
      var _a;
      const jsonStr = textarea.value.trim();
      if (!jsonStr) {
        new import_obsidian3.Notice("\u8BF7\u5148\u7C98\u8D34\u914D\u7F6E JSON");
        return;
      }
      importBtn.disabled = true;
      importBtn.textContent = "\u5BFC\u5165\u4E2D\u2026";
      try {
        const ok = await this.plugin.importConfig(jsonStr);
        if (ok) {
          this.close();
          (_a = this.plugin.settingTab) == null ? void 0 : _a.display();
        } else {
          importBtn.disabled = false;
          importBtn.textContent = "\u{1F4E5} \u5BFC\u5165";
        }
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        new import_obsidian3.Notice(`\u274C \u5BFC\u5165\u5931\u8D25\uFF1A${msg}`, 8e3);
        importBtn.disabled = false;
        importBtn.textContent = "\u{1F4E5} \u5BFC\u5165";
      }
    });
    const cancelBtn = btnContainer.createEl("button", {
      text: "\u53D6\u6D88",
      attr: { style: "flex: 1; cursor: pointer;" }
    });
    cancelBtn.addEventListener("click", () => this.close());
  }
  onClose() {
    this.contentEl.empty();
  }
};
var SettingsTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.logInterval = null;
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    try {
      containerEl.createEl("h2", { text: "Dropbox \u540C\u6B65" });
      containerEl.createEl("h3", { text: "\u6388\u6743" });
      const token = loadToken(this.plugin.settings.dropboxToken);
      const isAuthed = isTokenValid(token);
      const statusEl = containerEl.createEl("div", {
        cls: `dropbox-sync-auth-status ${isAuthed ? "authorized" : "unauthorized"}`
      });
      statusEl.textContent = isAuthed ? "\u2705 \u5DF2\u6388\u6743 Dropbox" : "\u274C \u672A\u6388\u6743 \u2014 \u8BF7\u5728\u4E0B\u65B9\u586B\u5199 App Key \u5E76\u6388\u6743";
      const engineStatus = containerEl.createEl("div", {
        attr: { style: "margin: 8px 0; padding: 6px; background: var(--background-secondary); border-radius: 4px; font-size: 12px;" }
      });
      const eng = this.plugin.syncEngine;
      const tok = token;
      engineStatus.innerHTML = `\u5F15\u64CE: ${eng ? "\u2705 \u5DF2\u52A0\u8F7D" : "\u274C \u672A\u52A0\u8F7D"}<br>Token: ${tok ? "\u2705 access(" + tok.access_token.slice(0, 6) + "...)" + (!tok.refresh_token ? " \u274C\u65E0refresh" : " \u2705\u6709refresh") : "\u274C \u65E0"}`;
      new import_obsidian3.Setting(containerEl).setName("Dropbox App Key").setDesc(
        "\u5728 https://www.dropbox.com/developers/apps \u521B\u5EFA\u5E94\u7528\uFF0C\u590D\u5236 App Key \u7C98\u8D34\u81F3\u6B64"
      ).addText(
        (text) => text.setPlaceholder("\u4F60\u7684 Dropbox App Key").setValue(this.plugin.settings.clientId).onChange(async (value) => {
          this.plugin.settings.clientId = value;
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian3.Setting(containerEl).addButton((btn) => {
        btn.setButtonText(isAuthed ? "\u91CD\u65B0\u6388\u6743" : "\u6388\u6743 Dropbox").setCta().onClick(async () => {
          if (!this.plugin.settings.clientId) {
            new import_obsidian3.Notice("\u8BF7\u5148\u586B\u5199 Dropbox App Key");
            return;
          }
          try {
            btn.setDisabled(true);
            btn.setButtonText("\u6388\u6743\u4E2D\u2026");
            await this.plugin.authorizeDropbox();
            new import_obsidian3.Notice("Dropbox \u6388\u6743\u6210\u529F\uFF01");
            this.display();
          } catch (err) {
            const msg = err instanceof Error ? err.message : String(err);
            new import_obsidian3.Notice(`\u6388\u6743\u5931\u8D25\uFF1A${msg}`, 8e3);
          } finally {
            btn.setDisabled(false);
            this.display();
          }
        });
      });
      if (isAuthed) {
        new import_obsidian3.Setting(containerEl).addButton((btn) => {
          btn.setButtonText("\u64A4\u9500\u6388\u6743").setWarning().onClick(async () => {
            await this.plugin.revokeDropbox();
            new import_obsidian3.Notice("\u5DF2\u64A4\u9500 Dropbox \u6388\u6743");
            this.display();
          });
        });
      }
      containerEl.createEl("h3", { text: "\u540C\u6B65\u8BBE\u7F6E" });
      new import_obsidian3.Setting(containerEl).setName("\u540C\u6B65\u65B9\u5411").setDesc("\u4E0A\u4F20\uFF1A\u5E93 \u2192 Dropbox\uFF08\u5B89\u5168\uFF09\u3002\u4E0B\u8F7D\uFF1ADropbox \u2192 \u5E93\u3002\u53CC\u5411\uFF1A\u4E24\u8FB9\u5408\u5E76\u3002").addDropdown(
        (dropdown) => dropdown.addOption("upload", "\u4E0A\u4F20\uFF08\u5E93 \u2192 Dropbox\uFF09").addOption("download", "\u4E0B\u8F7D\uFF08Dropbox \u2192 \u5E93\uFF09").addOption("two-way", "\u53CC\u5411\u540C\u6B65").setValue(this.plugin.settings.syncDirection).onChange(async (value) => {
          this.plugin.settings.syncDirection = value;
          await this.plugin.saveSettings();
          this.plugin.reloadSyncEngine();
        })
      );
      new import_obsidian3.Setting(containerEl).setName("\u8FDC\u7A0B\u8DEF\u5F84").setDesc("Dropbox \u4E0A\u7684\u540C\u6B65\u76EE\u5F55\uFF08\u4F8B\u5982 /Apps/ObsidianSync\uFF09").addText(
        (text) => text.setPlaceholder("/Apps/ObsidianSync").setValue(this.plugin.settings.remotePath).onChange(async (value) => {
          const normalized = value.startsWith("/") ? value : "/" + value;
          this.plugin.settings.remotePath = normalized || "/Apps/ObsidianSync";
          await this.plugin.saveSettings();
          this.plugin.reloadSyncEngine();
        })
      );
      new import_obsidian3.Setting(containerEl).setName("\u672C\u5730\u8DEF\u5F84\u524D\u7F00").setDesc("\u53EA\u540C\u6B65\u5E93\u7684\u67D0\u4E2A\u5B50\u6587\u4EF6\u5939\uFF08\u7559\u7A7A = \u6574\u4E2A\u5E93\uFF09\uFF0C\u4F8B\u5982\u300C\u7B14\u8BB0\u300D").addText(
        (text) => text.setPlaceholder("\u7559\u7A7A\u5219\u540C\u6B65\u6574\u4E2A\u5E93").setValue(this.plugin.settings.localPrefix).onChange(async (value) => {
          this.plugin.settings.localPrefix = value;
          await this.plugin.saveSettings();
          this.plugin.reloadSyncEngine();
        })
      );
      new import_obsidian3.Setting(containerEl).setName("\u6700\u5927\u6587\u4EF6\u5927\u5C0F").setDesc("\u8D85\u8FC7\u6B64\u5927\u5C0F\u7684\u6587\u4EF6\u5C06\u88AB\u8DF3\u8FC7\uFF080 = \u4E0D\u9650\u5236\uFF0C\u9ED8\u8BA4 50MB\uFF09").addText(
        (text) => text.setPlaceholder("52428800").setValue(String(this.plugin.settings.maxFileSize)).onChange(async (value) => {
          const num = parseInt(value, 10);
          if (!isNaN(num) && num >= 0) {
            this.plugin.settings.maxFileSize = num;
            await this.plugin.saveSettings();
          }
        })
      );
      new import_obsidian3.Setting(containerEl).setName("\u4FDD\u5B58\u65F6\u81EA\u52A8\u540C\u6B65").setDesc("\u6587\u4EF6\u5728 Obsidian \u4E2D\u4FDD\u5B58\u540E\u81EA\u52A8\u4E0A\u4F20\u5230 Dropbox").addToggle(
        (toggle) => toggle.setValue(this.plugin.settings.syncOnSave).onChange(async (value) => {
          this.plugin.settings.syncOnSave = value;
          await this.plugin.saveSettings();
        })
      );
      containerEl.createEl("h3", { text: "\u624B\u52A8\u540C\u6B65" });
      new import_obsidian3.Setting(containerEl).addButton((btn) => {
        btn.setButtonText("\u{1F504} \u7ACB\u5373\u540C\u6B65").setCta().onClick(async () => {
          if (!this.plugin.syncEngine) {
            new import_obsidian3.Notice("\u8BF7\u5148\u6388\u6743 Dropbox");
            return;
          }
          try {
            btn.setDisabled(true);
            btn.setButtonText("\u540C\u6B65\u4E2D\u2026");
            const result = await this.plugin.syncEngine.syncNow();
            this.plugin.settings.lastSyncAt = result.lastSyncAt;
            await this.plugin.saveSettings();
            new import_obsidian3.Notice("\u540C\u6B65\u5B8C\u6210\uFF01");
          } catch (err) {
            const msg = err instanceof Error ? err.message : String(err);
            new import_obsidian3.Notice(`\u540C\u6B65\u5931\u8D25\uFF1A${msg}`, 8e3);
          } finally {
            btn.setDisabled(false);
            btn.setButtonText("\u{1F504} \u7ACB\u5373\u540C\u6B65");
          }
        });
      });
      new import_obsidian3.Setting(containerEl).addButton((btn) => {
        btn.setButtonText("\u53D6\u6D88\u540C\u6B65").setWarning().onClick(() => {
          var _a;
          (_a = this.plugin.syncEngine) == null ? void 0 : _a.cancel();
          new import_obsidian3.Notice("\u540C\u6B65\u5DF2\u53D6\u6D88");
        });
      });
      new import_obsidian3.Setting(containerEl).addButton((btn) => {
        btn.setButtonText("\u{1F195} \u9996\u6B21\u540C\u6B65\uFF08\u6E05\u7A7A\u72B6\u6001\u91CD\u626B\uFF09").setCta().onClick(async () => {
          if (!this.plugin.syncEngine) {
            new import_obsidian3.Notice("\u8BF7\u5148\u6388\u6743 Dropbox");
            return;
          }
          try {
            btn.setDisabled(true);
            btn.setButtonText("\u540C\u6B65\u4E2D\u2026");
            const result = await this.plugin.syncEngine.syncFresh();
            this.plugin.settings.lastSyncAt = result.lastSyncAt;
            await this.plugin.saveSettings();
            new import_obsidian3.Notice("\u9996\u6B21\u540C\u6B65\u5B8C\u6210\uFF01");
          } catch (err) {
            const msg = err instanceof Error ? err.message : String(err);
            new import_obsidian3.Notice(`\u540C\u6B65\u5931\u8D25\uFF1A${msg}`, 8e3);
          } finally {
            btn.setDisabled(false);
            btn.setButtonText("\u{1F195} \u9996\u6B21\u540C\u6B65\uFF08\u6E05\u7A7A\u72B6\u6001\u91CD\u626B\uFF09");
          }
        });
      });
      containerEl.createEl("h3", { text: "\u914D\u7F6E\u5BFC\u5165\u5BFC\u51FA" });
      new import_obsidian3.Setting(containerEl).setName("\u5BFC\u51FA\u914D\u7F6E\u5230\u526A\u8D34\u677F").setDesc("\u5C06\u5F53\u524D\u6240\u6709\u8BBE\u7F6E\uFF08\u5305\u62EC Token\uFF09\u590D\u5236\u5230\u526A\u8D34\u677F\uFF0C\u53EF\u5728\u53E6\u4E00\u53F0\u8BBE\u5907\u4E0A\u5BFC\u5165").addButton(
        (btn) => btn.setButtonText("\u{1F4CB} \u5BFC\u51FA\u914D\u7F6E").setCta().onClick(async () => {
          await this.plugin.exportConfigToClipboard();
        })
      );
      new import_obsidian3.Setting(containerEl).setName("\u4ECE\u526A\u8D34\u677F\u5BFC\u5165\u914D\u7F6E").setDesc("\u7C98\u8D34\u4E4B\u524D\u5BFC\u51FA\u7684 JSON \u914D\u7F6E\uFF0C\u8986\u76D6\u5F53\u524D\u6240\u6709\u8BBE\u7F6E").addButton(
        (btn) => btn.setButtonText("\u{1F4E5} \u5BFC\u5165\u914D\u7F6E").onClick(() => {
          const modal = new ImportModal(this.app, this.plugin);
          modal.open();
        })
      );
      containerEl.createEl("h3", { text: "\u540C\u6B65\u65E5\u5FD7" });
      const logContainer = containerEl.createDiv();
      const logTextarea = logContainer.createEl("textarea", {
        attr: {
          readonly: "readonly",
          rows: "10",
          style: "width: 100%; font-family: monospace; font-size: 12px; box-sizing: border-box; resize: vertical; white-space: pre;"
        }
      });
      const updateLog = () => {
        logTextarea.value = getLogs().join("\n");
        logTextarea.scrollTop = logTextarea.scrollHeight;
      };
      updateLog();
      this.logInterval = window.setInterval(updateLog, 2e3);
      const refreshBtn = logContainer.createEl("button", {
        text: "\u{1F504} \u5237\u65B0\u65E5\u5FD7",
        attr: { style: "cursor: pointer; margin-right: 8px;" }
      });
      refreshBtn.addEventListener("click", updateLog);
      const clearBtn = logContainer.createEl("button", {
        text: "\u{1F5D1} \u6E05\u7A7A",
        attr: { style: "cursor: pointer;" }
      });
      clearBtn.addEventListener("click", () => {
        clearLogs();
        logTextarea.value = "";
      });
      containerEl.createEl("h3", { text: "\u8BBE\u7F6E\u6B65\u9AA4" });
      const infoEl = containerEl.createEl("div", { cls: "setting-item-description" });
      infoEl.innerHTML = `
				<ol>
					<li>\u524D\u5F80 <a href="https://www.dropbox.com/developers/apps" target="_blank">Dropbox \u5F00\u53D1\u8005\u63A7\u5236\u53F0</a></li>
					<li>\u521B\u5EFA\u65B0\u5E94\u7528 \u2192 "Scoped access" \u2192 "App folder" \u6216 "Full Dropbox"</li>
					<li>\u5728 <strong>Permissions</strong> \u6807\u7B7E\u9875\u52FE\u9009\uFF1A<code>files.metadata.read</code>\u3001<code>files.content.read</code>\u3001<code>files.content.write</code></li>
					<li>\u5728 <strong>OAuth 2</strong> \u4E2D\u8BBE\u7F6E\u91CD\u5B9A\u5411 URI\uFF1A<code>http://127.0.0.1:54219/</code></li>
					<li>\u590D\u5236 <strong>App Key</strong> \u7C98\u8D34\u5230\u4E0A\u65B9\u8F93\u5165\u6846</li>
					<li>\u70B9\u51FB "\u6388\u6743 Dropbox" \u2192 \u5728\u6D4F\u89C8\u5668\u4E2D\u5B8C\u6210\u6388\u6743</li>
					<li>\u6388\u6743\u540E\u6D4F\u89C8\u5668\u8DF3\u8F6C\u5230 <code>http://127.0.0.1:54219/</code>\uFF08\u663E\u793A\u65E0\u6CD5\u8BBF\u95EE \u2014 \u6B63\u5E38\uFF09</li>
					<li>\u590D\u5236\u6D4F\u89C8\u5668\u5730\u5740\u680F\u7684\u5B8C\u6574\u7F51\u5740 \u2192 \u56DE\u5230 Obsidian \u2192 \u7C98\u8D34\u5230\u5F39\u51FA\u7684\u5BF9\u8BDD\u6846</li>
				</ol>
				<p>\u6388\u6743\u540E\uFF0C\u4F60\u7684\u5E93\u4F1A\u81EA\u52A8\u540C\u6B65\u5230 Dropbox \u7684 <code>${this.plugin.settings.remotePath}/</code> \u76EE\u5F55\u3002</p>
			`;
    } catch (err) {
      console.error("Dropbox Sync: display error", err);
    }
  }
};

// src/main.ts
var DropboxSyncPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.syncEngine = null;
    this.settingTab = null;
    this.statusBarItem = null;
    this.statusInterval = null;
    this.debouncedUpload = this.debounce(async (file) => {
      if (!this.syncEngine)
        return;
      await this.syncEngine.uploadFile(file);
      this.refreshStatusBar();
    }, 2e3);
  }
  // ─── Lifecycle ───────────────────────────────────────────────────────────
  async onload() {
    await this.loadSettings();
    this.statusBarItem = this.addStatusBarItem();
    this.statusBarItem.addClass("dropbox-sync-status-bar");
    this.updateStatusBar("idle");
    this.settingTab = new SettingsTab(this.app, this);
    this.addSettingTab(this.settingTab);
    this.registerCommands();
    this.registerEventHooks();
    this.initSyncEngine();
    this.statusInterval = window.setInterval(() => this.refreshStatusBar(), 5e3);
  }
  onunload() {
    var _a;
    (_a = this.syncEngine) == null ? void 0 : _a.cancel();
    if (this.statusInterval !== null) {
      clearInterval(this.statusInterval);
    }
  }
  // ─── Sync Engine ─────────────────────────────────────────────────────────
  initSyncEngine() {
    var _a;
    const token = loadToken(this.settings.dropboxToken);
    if (!isTokenValid(token)) {
      if (token) {
        new import_obsidian4.Notice(`\u274C Token \u7F3A\u5C11 refresh_token\uFF08\u503C\u4E3A\u7A7A\uFF09\uFF0C\u8BF7\u91CD\u65B0\u6388\u6743`, 8e3);
      } else {
        const raw = this.settings.dropboxToken;
        new import_obsidian4.Notice(`\u274C Token \u52A0\u8F7D\u5931\u8D25: type=${typeof raw}, keys=${raw ? Object.keys(raw).join(",") : "null"}`, 8e3);
      }
      this.syncEngine = null;
      return;
    }
    const adapter = this.app.vault.adapter;
    const basePath = (_a = adapter == null ? void 0 : adapter.getBasePath) == null ? void 0 : _a.call(adapter);
    const segments = [basePath, this.app.vault.configDir || ".obsidian", "plugins", this.manifest.id];
    const pluginDir = basePath ? segments.filter(Boolean).join("/").replace(/\\/g, "/").replace(/([^:])\/+/g, "$1/") : "";
    const stateFilePath = basePath ? pluginDir + "/state.json" : ".obsidian/plugins/" + this.manifest.id + "/state.json";
    addLog("\u72B6\u6001\u6587\u4EF6\u8DEF\u5F84: " + stateFilePath);
    this.syncEngine = new SyncEngine(this.app.vault, token, {
      direction: this.settings.syncDirection,
      remoteBasePath: this.settings.remotePath,
      localPrefix: this.settings.localPrefix,
      maxFileSize: this.settings.maxFileSize,
      clientId: this.settings.clientId,
      stateFilePath
    });
  }
  /**
   * Re-create the sync engine (e.g. after auth or settings change).
   */
  reloadSyncEngine() {
    var _a;
    (_a = this.syncEngine) == null ? void 0 : _a.cancel();
    this.initSyncEngine();
  }
  // ─── OAuth ───────────────────────────────────────────────────────────────
  /**
   * Start Dropbox authorization flow.
   */
  async authorizeDropbox() {
    const config = {
      clientId: this.settings.clientId
    };
    try {
      const token = await authorize(config);
      Object.assign(this.settings, saveToken(token));
      await this.saveSettings();
      this.reloadSyncEngine();
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      throw new Error(`Authorization failed: ${msg}`);
    }
  }
  /**
   * Revoke Dropbox authorization.
   */
  async revokeDropbox() {
    var _a;
    Object.assign(this.settings, clearToken());
    await this.saveSettings();
    (_a = this.syncEngine) == null ? void 0 : _a.cancel();
    this.syncEngine = null;
  }
  // ─── Config Export / Import ──────────────────────────────────────────────
  /**
   * 导出配置：优先剪贴板，失败则弹窗显示 JSON。
   */
  async exportConfigToClipboard() {
    const exportData = {};
    for (const [key, value] of Object.entries(this.settings)) {
      exportData[key] = value;
    }
    const jsonStr = JSON.stringify(exportData, null, 2);
    try {
      await navigator.clipboard.writeText(jsonStr);
      new import_obsidian4.Notice("\u2705 \u914D\u7F6E\u5DF2\u590D\u5236\u5230\u526A\u8D34\u677F", 3e3);
    } catch (e) {
      new ExportModal(this.app, jsonStr).open();
    }
  }
  /**
   * 从 JSON 字符串导入配置并应用。
   * @param jsonStr 用户粘贴的 JSON 字符串
   * @returns 导入是否成功
   */
  async importConfig(jsonStr) {
    let parsed;
    try {
      parsed = JSON.parse(jsonStr);
    } catch (e) {
      new import_obsidian4.Notice("\u274C \u914D\u7F6E\u683C\u5F0F\u9519\u8BEF\uFF1A\u4E0D\u662F\u6709\u6548\u7684 JSON", 5e3);
      return false;
    }
    if (typeof parsed !== "object" || parsed === null) {
      new import_obsidian4.Notice("\u274C \u914D\u7F6E\u683C\u5F0F\u9519\u8BEF\uFF1A\u9700\u8981 JSON \u5BF9\u8C61", 5e3);
      return false;
    }
    const errors = [];
    if (parsed.clientId !== void 0 && typeof parsed.clientId !== "string") {
      errors.push("clientId \u5E94\u4E3A\u5B57\u7B26\u4E32");
    }
    if (parsed.syncDirection !== void 0 && !["upload", "download", "two-way"].includes(parsed.syncDirection)) {
      errors.push("syncDirection \u5E94\u4E3A upload / download / two-way");
    }
    if (parsed.maxFileSize !== void 0 && typeof parsed.maxFileSize !== "number") {
      errors.push("maxFileSize \u5E94\u4E3A\u6570\u5B57");
    }
    if (parsed.syncOnSave !== void 0 && typeof parsed.syncOnSave !== "boolean") {
      errors.push("syncOnSave \u5E94\u4E3A\u5E03\u5C14\u503C");
    }
    if (errors.length > 0) {
      new import_obsidian4.Notice(`\u274C \u914D\u7F6E\u6821\u9A8C\u5931\u8D25\uFF1A${errors.join("\uFF1B")}`, 8e3);
      return false;
    }
    Object.assign(this.settings, DEFAULT_SETTINGS, parsed);
    await this.saveSettings();
    try {
      this.reloadSyncEngine();
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      new import_obsidian4.Notice(`\u26A0\uFE0F \u914D\u7F6E\u5DF2\u4FDD\u5B58\uFF0C\u4F46\u5F15\u64CE\u52A0\u8F7D\u5931\u8D25\uFF1A${msg}`, 8e3);
      console.warn("Dropbox Sync: \u5BFC\u5165\u540E\u91CD\u8F7D\u5F15\u64CE\u5931\u8D25", err);
    }
    if (this.syncEngine) {
      new import_obsidian4.Notice("\u2705 \u914D\u7F6E\u5BFC\u5165\u6210\u529F\uFF0C\u5F15\u64CE\u5DF2\u5C31\u7EEA", 3e3);
    } else {
      new import_obsidian4.Notice("\u26A0\uFE0F \u914D\u7F6E\u5DF2\u4FDD\u5B58\uFF0C\u4F46\u5F15\u64CE\u672A\u52A0\u8F7D\uFF08\u68C0\u67E5 Token \u662F\u5426\u6709\u6548\uFF09", 8e3);
    }
    return true;
  }
  // ─── Commands ────────────────────────────────────────────────────────────
  registerCommands() {
    this.addCommand({
      id: "sync-now",
      name: "\u7ACB\u5373\u5168\u91CF\u540C\u6B65",
      callback: async () => {
        if (!this.syncEngine) {
          new import_obsidian4.Notice("Dropbox \u540C\u6B65\uFF1A\u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u6388\u6743");
          return;
        }
        try {
          const result = await this.syncEngine.syncNow();
          this.settings.lastSyncAt = result.lastSyncAt;
          await this.saveSettings();
          addLog("\u540C\u6B65\u5B8C\u6210: " + JSON.stringify(result));
          this.refreshStatusBar();
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          new import_obsidian4.Notice(`Dropbox \u540C\u6B65\u9519\u8BEF\uFF1A${msg}`, 8e3);
        }
      }
    });
    this.addCommand({
      id: "cancel-sync",
      name: "\u53D6\u6D88\u540C\u6B65",
      callback: () => {
        var _a;
        (_a = this.syncEngine) == null ? void 0 : _a.cancel();
        new import_obsidian4.Notice("Dropbox \u540C\u6B65\u5DF2\u53D6\u6D88");
      }
    });
  }
  // ─── Events ──────────────────────────────────────────────────────────────
  registerEventHooks() {
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (!this.syncEngine || !this.settings.syncOnSave)
          return;
        if (!this.syncEngine.shouldSync(file))
          return;
        this.debouncedUpload(file);
      })
    );
    this.registerEvent(
      this.app.vault.on("create", (file) => {
        if (!this.syncEngine || !this.settings.syncOnSave)
          return;
        if (!this.syncEngine.shouldSync(file))
          return;
        this.debouncedUpload(file);
      })
    );
  }
  // ─── Status Bar ──────────────────────────────────────────────────────────
  refreshStatusBar() {
    if (!this.statusBarItem)
      return;
    if (!this.syncEngine) {
      this.updateStatusBar("unauthorized");
      return;
    }
    const status = this.syncEngine.getStatus();
    if (status.running) {
      this.updateStatusBar("syncing", status);
    } else if (status.lastError) {
      this.updateStatusBar("error", status);
    } else if (status.lastSyncAt) {
      this.updateStatusBar("synced", status);
    } else {
      this.updateStatusBar("idle");
    }
  }
  updateStatusBar(state, status) {
    var _a, _b;
    if (!this.statusBarItem)
      return;
    this.statusBarItem.empty();
    this.statusBarItem.className = `dropbox-sync-status-bar ${state}`;
    switch (state) {
      case "unauthorized":
        this.statusBarItem.setText("\u2601\uFE0F Dropbox \u2014 \u672A\u6388\u6743");
        break;
      case "syncing":
        this.statusBarItem.setText(
          `\u2601\uFE0F \u540C\u6B65\u4E2D\u2026 ${(_a = status == null ? void 0 : status.progress.completed) != null ? _a : 0}/${(_b = status == null ? void 0 : status.progress.total) != null ? _b : 0}`
        );
        break;
      case "synced": {
        const last = (status == null ? void 0 : status.lastSyncAt) ? new Date(status.lastSyncAt).toLocaleTimeString() : "?";
        this.statusBarItem.setText(`\u2601\uFE0F \u5DF2\u540C\u6B65 ${last}`);
        break;
      }
      case "error":
        this.statusBarItem.setText("\u2601\uFE0F \u540C\u6B65\u51FA\u9519");
        break;
      default:
        this.statusBarItem.setText("\u2601\uFE0F Dropbox");
        break;
    }
  }
  // ─── Settings ────────────────────────────────────────────────────────────
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data);
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // ─── Utility ─────────────────────────────────────────────────────────────
  debounce(fn, delay) {
    let timer = null;
    return (...args) => {
      if (timer !== null)
        clearTimeout(timer);
      timer = window.setTimeout(() => {
        fn(...args);
        timer = null;
      }, delay);
    };
  }
};
