/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DropboxSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/sync-engine.ts
var import_obsidian2 = require("obsidian");

// src/dropbox-auth.ts
var import_obsidian = require("obsidian");
function generateCodeVerifier() {
  const charset = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~";
  const array = new Uint8Array(64);
  crypto.getRandomValues(array);
  return Array.from(array, (byte) => charset[byte % charset.length]).join("");
}
async function generateCodeChallenge(verifier) {
  const encoder = new TextEncoder();
  const data = encoder.encode(verifier);
  const digest = await crypto.subtle.digest("SHA-256", data);
  return btoa(String.fromCharCode(...new Uint8Array(digest))).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}
function loadToken(raw) {
  if (!raw || typeof raw !== "object")
    return null;
  const t = raw;
  if (typeof t.access_token !== "string" || typeof t.refresh_token !== "string" || typeof t.expires_at !== "number") {
    return null;
  }
  return {
    access_token: t.access_token,
    refresh_token: t.refresh_token,
    expires_at: t.expires_at,
    account_id: typeof t.account_id === "string" ? t.account_id : void 0
  };
}
function saveToken(token) {
  var _a;
  return {
    dropboxToken: {
      access_token: token.access_token,
      refresh_token: token.refresh_token,
      expires_at: token.expires_at,
      account_id: (_a = token.account_id) != null ? _a : void 0
    }
  };
}
function clearToken() {
  return { dropboxToken: null };
}
function isTokenExpired(token) {
  return Date.now() >= token.expires_at - 3e5;
}
function isTokenValid(token) {
  if (!token)
    return false;
  return !!token.access_token && !!token.refresh_token;
}
var REDIRECT_PORT = 54219;
var REDIRECT_URI = `http://127.0.0.1:${REDIRECT_PORT}/`;
async function authorize(config) {
  const verifier = generateCodeVerifier();
  const challenge = await generateCodeChallenge(verifier);
  const state = generateCodeVerifier();
  let serverResult = null;
  try {
    console.log("Dropbox Sync: \u5C1D\u8BD5\u542F\u52A8\u672C\u5730 HTTP \u670D\u52A1\u5668...");
    serverResult = await startHttpServer();
    console.log("Dropbox Sync: \u672C\u5730\u670D\u52A1\u5668\u5DF2\u542F\u52A8\uFF0C\u7AEF\u53E3", REDIRECT_PORT);
  } catch (err) {
    console.warn("Dropbox Sync: \u672C\u5730\u670D\u52A1\u5668\u542F\u52A8\u5931\u8D25\uFF0C\u5C06\u4F7F\u7528\u624B\u52A8\u6A21\u5F0F", err);
  }
  const scopes = "files.metadata.read files.content.read files.content.write";
  const authUrl = `https://www.dropbox.com/oauth2/authorize?client_id=${encodeURIComponent(config.clientId)}&response_type=code&redirect_uri=${encodeURIComponent(REDIRECT_URI)}&code_challenge=${encodeURIComponent(challenge)}&code_challenge_method=S256&state=${encodeURIComponent(state)}&token_access_type=offline&scope=${encodeURIComponent(scopes)}`;
  new import_obsidian.Notice("\u6B63\u5728\u6253\u5F00\u6D4F\u89C8\u5668\u8FDB\u884C Dropbox \u6388\u6743\u2026");
  openUrl(authUrl);
  let code;
  if (serverResult) {
    console.log("Dropbox Sync: \u7B49\u5F85\u672C\u5730\u56DE\u8C03...");
    const result = await serverResult.promise;
    if (result.state !== state) {
      throw new Error("State \u4E0D\u5339\u914D \u2014 \u53EF\u80FD\u662F CSRF \u653B\u51FB");
    }
    code = result.code;
    console.log("Dropbox Sync: \u901A\u8FC7\u672C\u5730\u670D\u52A1\u5668\u6536\u5230\u6388\u6743\u7801");
  } else {
    code = await promptForCode(state);
  }
  return await exchangeCodeForToken(config.clientId, REDIRECT_URI, verifier, code);
}
async function startHttpServer() {
  let resolveCode;
  let rejectCode;
  const codePromise = new Promise((res, rej) => {
    resolveCode = res;
    rejectCode = rej;
  });
  const http = require("http");
  const url_mod = require("url");
  console.log("Dropbox Sync: require('http') \u6210\u529F");
  const server = http.createServer((req, res) => {
    const parsed = url_mod.parse(req.url || "", true);
    const code = parsed.query.code;
    const state = parsed.query.state;
    console.log("Dropbox Sync: \u6536\u5230\u56DE\u8C03", req.url);
    if (code) {
      res.writeHead(200, { "Content-Type": "text/html; charset=utf-8" });
      res.end(`<html><body><h2>\u2713 \u6388\u6743\u6210\u529F\uFF01</h2><p>\u4F60\u53EF\u4EE5\u5173\u95ED\u6B64\u9875\u9762\u4E86\u3002</p></body></html>`);
      server.close();
      resolveCode({ code, state });
    } else {
      res.writeHead(400, { "Content-Type": "text/html; charset=utf-8" });
      res.end(`<html><body><h2>\u2717 \u6388\u6743\u5931\u8D25</h2><p>\u672A\u6536\u5230\u6388\u6743\u7801\u3002</p></body></html>`);
      server.close();
      rejectCode(new Error("\u672A\u6536\u5230\u6388\u6743\u7801"));
    }
  });
  await new Promise((resolve, reject) => {
    server.on("error", (err) => {
      console.error("Dropbox Sync: \u670D\u52A1\u5668\u9519\u8BEF", err);
      reject(err);
    });
    server.listen(REDIRECT_PORT, "127.0.0.1", () => {
      console.log("Dropbox Sync: \u670D\u52A1\u5668\u5DF2\u542F\u52A8", REDIRECT_PORT);
      resolve();
    });
  });
  return { promise: codePromise };
}
async function promptForCode(expectedState) {
  const message = "\u2705 Dropbox \u6388\u6743\u7A97\u53E3\u5DF2\u6253\u5F00\n\n1. \u5728\u6D4F\u89C8\u5668\u4E2D\u5B8C\u6210\u6388\u6743\n2. \u6388\u6743\u540E\u6D4F\u89C8\u5668\u4F1A\u8DF3\u8F6C\u5230 http://127.0.0.1:54219/ \uFF08\u9875\u9762\u65E0\u6CD5\u8BBF\u95EE\u662F\u6B63\u5E38\u7684\uFF09\n3. \u590D\u5236\u6D4F\u89C8\u5668\u5730\u5740\u680F\u7684\u5B8C\u6574\u7F51\u5740\n4. \u70B9\u51FB\u786E\u5B9A\uFF0C\u7C98\u8D34\u5230\u4E0B\u9762\u7684\u8F93\u5165\u6846\n\n\u5982\u8BEF\u5173\u4E86\u6D4F\u89C8\u5668\uFF0C\u70B9\u51FB\u300C\u53D6\u6D88\u300D\u540E\u91CD\u65B0\u6388\u6743\u3002";
  const url = prompt(message);
  if (!url) {
    throw new Error("\u7528\u6237\u53D6\u6D88\u4E86\u6388\u6743");
  }
  try {
    const parsed = new URL(url);
    const code = parsed.searchParams.get("code");
    const state = parsed.searchParams.get("state");
    if (!code) {
      throw new Error("\u7F51\u5740\u4E2D\u672A\u627E\u5230\u6388\u6743\u7801 (code)\uFF0C\u8BF7\u786E\u8BA4\u590D\u5236\u7684\u662F\u5B8C\u6574\u5730\u5740\u680F\u5185\u5BB9");
    }
    if (state !== expectedState) {
      throw new Error("State \u4E0D\u5339\u914D \u2014 \u53EF\u80FD\u662F CSRF \u653B\u51FB\uFF0C\u8BF7\u91CD\u65B0\u6388\u6743");
    }
    return code;
  } catch (err) {
    if (err instanceof TypeError && err.message.includes("URL")) {
      throw new Error("\u7F51\u5740\u683C\u5F0F\u4E0D\u6B63\u786E\uFF0C\u8BF7\u590D\u5236\u6D4F\u89C8\u5668\u5730\u5740\u680F\u6574\u6BB5\u5185\u5BB9");
    }
    throw err;
  }
}
async function exchangeCodeForToken(clientId, redirectUri, codeVerifier, code) {
  var _a, _b;
  const body = new URLSearchParams({
    code,
    grant_type: "authorization_code",
    client_id: clientId,
    redirect_uri: redirectUri,
    code_verifier: codeVerifier
  });
  const response = await (0, import_obsidian.requestUrl)({
    url: "https://api.dropboxapi.com/oauth2/token",
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: body.toString()
  });
  if (response.status !== 200) {
    const err = JSON.parse(response.text);
    throw new Error(`Dropbox \u6388\u6743\u9519\u8BEF\uFF1A${err.error} \u2014 ${(_a = err.error_description) != null ? _a : ""}`);
  }
  const data = JSON.parse(response.text);
  return {
    access_token: data.access_token,
    refresh_token: (_b = data.refresh_token) != null ? _b : "",
    expires_at: Date.now() + data.expires_in * 1e3,
    account_id: data.account_id
  };
}
async function refreshToken(clientId, token) {
  var _a, _b, _c;
  if (!token.refresh_token) {
    throw new Error("\u6CA1\u6709 refresh token \u2014 \u8BF7\u91CD\u65B0\u6388\u6743");
  }
  const body = new URLSearchParams({
    refresh_token: token.refresh_token,
    grant_type: "refresh_token",
    client_id: clientId
  });
  const response = await (0, import_obsidian.requestUrl)({
    url: "https://api.dropboxapi.com/oauth2/token",
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: body.toString()
  });
  if (response.status !== 200) {
    const err = JSON.parse(response.text);
    throw new Error(`\u5237\u65B0 token \u5931\u8D25\uFF1A${err.error} \u2014 ${(_a = err.error_description) != null ? _a : ""}`);
  }
  const data = JSON.parse(response.text);
  return {
    access_token: data.access_token,
    refresh_token: (_b = data.refresh_token) != null ? _b : token.refresh_token,
    expires_at: Date.now() + data.expires_in * 1e3,
    account_id: (_c = data.account_id) != null ? _c : token.account_id
  };
}
function openUrl(url) {
  if (import_obsidian.Platform.isDesktop) {
    const { shell } = require("electron");
    shell.openExternal(url);
  } else {
    window.open(url, "_blank");
  }
}

// src/sync-engine.ts
var SyncEngine = class {
  constructor(vault, token, options) {
    this.abortController = null;
    this.vault = vault;
    this.token = token;
    this.options = {
      ...options,
      remoteBasePath: "/" + options.remoteBasePath.replace(/^\/+|\/+$/g, "")
    };
    this.status = {
      running: false,
      lastSyncAt: null,
      lastError: null,
      progress: { total: 0, completed: 0, current: "" }
    };
    console.log("Dropbox Sync: SyncEngine \u521B\u5EFA", {
      direction: options.direction,
      remoteBasePath: this.options.remoteBasePath,
      lastSyncAt: options.lastSyncAt ? new Date(options.lastSyncAt).toISOString() : "\u9996\u6B21",
      incrementalCount: options.incrementalCount
    });
  }
  getStatus() {
    return { ...this.status, progress: { ...this.status.progress } };
  }
  isRunning() {
    return this.status.running;
  }
  updateToken(token) {
    this.token = token;
  }
  /** 返回当前 sync options 供保存 */
  getOptions() {
    return { ...this.options };
  }
  // ─── 全量同步 ──────────────────────────────────────────────────────────
  async syncNow() {
    if (this.status.running) {
      console.warn("Dropbox Sync: \u540C\u6B65\u5DF2\u5728\u8FDB\u884C\u4E2D");
      throw new Error("\u540C\u6B65\u5DF2\u5728\u8FDB\u884C\u4E2D");
    }
    this.abortController = new AbortController();
    this.status.running = true;
    this.status.lastError = null;
    this.status.progress = { total: 0, completed: 0, current: "\u6B63\u5728\u542F\u52A8\u2026" };
    const needsFullScan = this.options.lastSyncAt === 0 || this.options.incrementalCount >= 10;
    console.log("Dropbox Sync: === \u5F00\u59CB\u540C\u6B65 ===");
    console.log("Dropbox Sync: \u65B9\u5411:", this.options.direction);
    console.log("Dropbox Sync: \u6A21\u5F0F:", needsFullScan ? "\u5168\u91CF" : "\u589E\u91CF");
    console.log("Dropbox Sync: \u589E\u91CF\u8BA1\u6570:", this.options.incrementalCount);
    try {
      await this.ensureValidToken();
      const result = await this.runSync(needsFullScan);
      this.status.lastSyncAt = Date.now();
      console.log("Dropbox Sync: === \u540C\u6B65\u5B8C\u6210 ===");
      new import_obsidian2.Notice("Dropbox \u540C\u6B65\u5B8C\u6210");
      return result;
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      this.status.lastError = msg;
      console.error("Dropbox Sync: === \u540C\u6B65\u5931\u8D25 ===", err);
      new import_obsidian2.Notice(`Dropbox \u540C\u6B65\u9519\u8BEF\uFF1A${msg}`, 8e3);
      throw err;
    } finally {
      this.status.running = false;
      this.abortController = null;
    }
  }
  cancel() {
    console.log("Dropbox Sync: \u7528\u6237\u53D6\u6D88\u4E86\u540C\u6B65");
    if (this.abortController) {
      this.abortController.abort();
      this.abortController = null;
    }
    this.status.running = false;
  }
  // ─── 单文件保存同步 ──────────────────────────────────────────────────
  async uploadFile(file) {
    if (this.status.running) {
      console.log("Dropbox Sync: \u5168\u91CF\u540C\u6B65\u4E2D\uFF0C\u8DF3\u8FC7\u4FDD\u5B58\u65F6\u540C\u6B65", file.path);
      return;
    }
    try {
      await this.ensureValidToken();
      const localPath = file.path;
      const remotePath = this.localToRemote(localPath);
      const content = await this.vault.readBinary(file);
      if (this.options.maxFileSize > 0 && content.byteLength > this.options.maxFileSize) {
        console.log("Dropbox Sync: \u6587\u4EF6\u8D85\u8FC7\u5927\u5C0F\u9650\u5236", localPath);
        return;
      }
      console.log("Dropbox Sync: \u4FDD\u5B58\u65F6\u4E0A\u4F20", localPath);
      await this.dropboxUpload(remotePath, content);
    } catch (err) {
      console.error(`Dropbox Sync: \u4FDD\u5B58\u65F6\u4E0A\u4F20\u5931\u8D25 ${file.path}:`, err);
    }
  }
  shouldSync(file) {
    if (file instanceof import_obsidian2.TFolder)
      return false;
    const path = file.path;
    if (this.options.localPrefix && !path.startsWith(this.options.localPrefix))
      return false;
    const basename = file.name;
    if (basename.startsWith("."))
      return false;
    if (basename === "desktop.ini")
      return false;
    if (path.startsWith(".obsidian/"))
      return false;
    if (basename.includes(".conflict."))
      return false;
    return true;
  }
  // ─── 内部同步逻辑 ────────────────────────────────────────────────────────
  async runSync(needsFullScan) {
    var _a;
    let remoteCursor = null;
    this.status.progress.current = "\u6B63\u5728\u7D22\u5F15\u672C\u5730\u6587\u4EF6\u2026";
    console.time("Dropbox Sync: \u7D22\u5F15\u672C\u5730");
    const localFiles = await this.indexLocalFiles(needsFullScan ? 0 : this.options.lastSyncAt);
    console.timeEnd("Dropbox Sync: \u7D22\u5F15\u672C\u5730");
    console.log("Dropbox Sync: \u672C\u5730\u6587\u4EF6\u6570:", localFiles.size);
    this.status.progress.current = "\u6B63\u5728\u7D22\u5F15\u8FDC\u7A0B\u6587\u4EF6\u2026";
    console.time("Dropbox Sync: \u7D22\u5F15\u8FDC\u7A0B");
    const remoteResult = await this.indexRemoteFiles(needsFullScan);
    console.timeEnd("Dropbox Sync: \u7D22\u5F15\u8FDC\u7A0B");
    console.log("Dropbox Sync: \u8FDC\u7A0B\u6587\u4EF6\u6570:", remoteResult.files.size);
    remoteCursor = remoteResult.cursor;
    console.time("Dropbox Sync: \u5BF9\u6BD4\u5DEE\u5F02");
    const actions = this.resolveActions(localFiles, remoteResult.files);
    console.timeEnd("Dropbox Sync: \u5BF9\u6BD4\u5DEE\u5F02");
    console.log("Dropbox Sync: \u64CD\u4F5C\u6570:", actions.length);
    if (actions.length > 0) {
      console.log("Dropbox Sync: \u64CD\u4F5C:", actions.map((a) => `${a.action}:${a.path}`).join(", "));
    }
    this.status.progress.total = actions.length;
    this.status.progress.completed = 0;
    for (const action of actions) {
      if ((_a = this.abortController) == null ? void 0 : _a.signal.aborted) {
        throw new Error("\u540C\u6B65\u5DF2\u53D6\u6D88");
      }
      this.status.progress.current = action.path;
      try {
        await this.executeAction(action);
      } catch (err) {
        console.error(`Dropbox Sync: \u64CD\u4F5C\u5931\u8D25 ${action.action} ${action.path}:`, err);
      }
      this.status.progress.completed++;
    }
    const newIncrementalCount = needsFullScan ? 0 : this.options.incrementalCount + 1;
    return {
      lastSyncAt: Date.now(),
      remoteCursor: remoteCursor != null ? remoteCursor : this.options.remoteCursor,
      incrementalCount: newIncrementalCount,
      fullScanDone: needsFullScan
    };
  }
  // ─── 索引本地（增量过滤） ─────────────────────────────────────────────
  async indexLocalFiles(since) {
    var _a;
    const files = /* @__PURE__ */ new Map();
    const allFiles = this.vault.getFiles();
    for (const file of allFiles) {
      if (!this.shouldSync(file))
        continue;
      const relPath = this.relativePath(file.path);
      try {
        const stat = await this.vault.adapter.stat(file.path);
        const mtime = (_a = stat == null ? void 0 : stat.mtime) != null ? _a : file.stat.mtime;
        if (since > 0 && mtime <= since)
          continue;
        files.set(relPath, mtime);
      } catch (err) {
        console.warn("Dropbox Sync: \u8BFB\u53D6\u6587\u4EF6\u5931\u8D25", file.path, err);
      }
    }
    return files;
  }
  // ─── 索引远程（增量游标 / 全量） ─────────────────────────────────────
  async indexRemoteFiles(fullScan) {
    const files = /* @__PURE__ */ new Map();
    let cursor = null;
    let hasMore = true;
    let pageCount = 0;
    const useCursor = !fullScan && !!this.options.remoteCursor;
    while (hasMore) {
      pageCount++;
      let result;
      try {
        if (cursor) {
          result = await this.dropboxListFolderContinue(cursor);
        } else if (useCursor) {
          result = await this.dropboxListFolderContinue(this.options.remoteCursor);
        } else {
          result = await this.dropboxListFolder(this.options.remoteBasePath);
        }
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        if (msg.includes("409") && msg.includes("not_found")) {
          console.log("Dropbox Sync: \u8FDC\u7A0B\u76EE\u5F55\u4E0D\u5B58\u5728\uFF0C\u81EA\u52A8\u521B\u5EFA");
          await this.createRemoteFolder();
          return { files, cursor: null };
        }
        console.error("Dropbox Sync: \u7D22\u5F15\u8FDC\u7A0B\u5931\u8D25", err);
        throw err;
      }
      for (const entry of result.entries) {
        if (entry[".tag"] === "file") {
          const file = entry;
          const relPath = this.relativeRemotePath(file.path_lower);
          files.set(relPath, {
            rev: file.rev,
            modified: new Date(file.server_modified).getTime(),
            content_hash: file.content_hash
          });
        }
      }
      cursor = result.cursor;
      hasMore = result.has_more;
    }
    return { files, cursor };
  }
  // ─── 对比差异 + 冲突检测 ───────────────────────────────────────────
  resolveActions(localFiles, remoteFiles) {
    var _a, _b, _c;
    const actions = [];
    const allPaths = /* @__PURE__ */ new Set([...localFiles.keys(), ...remoteFiles.keys()]);
    const dir = this.options.direction;
    for (const path of allPaths) {
      const localMtime = (_a = localFiles.get(path)) != null ? _a : null;
      const remote = (_b = remoteFiles.get(path)) != null ? _b : null;
      const remoteMtime = (_c = remote == null ? void 0 : remote.modified) != null ? _c : null;
      if (localMtime === null) {
        if (dir === "download" || dir === "two-way") {
          actions.push({ path, action: "download" });
        }
        continue;
      }
      if (remoteMtime === null) {
        if (dir === "upload" || dir === "two-way") {
          actions.push({ path, action: "upload" });
        }
        continue;
      }
      if (dir === "upload") {
        if (localMtime > remoteMtime)
          actions.push({ path, action: "upload" });
      } else if (dir === "download") {
        if (remoteMtime > localMtime)
          actions.push({ path, action: "download" });
      } else {
        if (localMtime > remoteMtime && remoteMtime > this.options.lastSyncAt + 1e3) {
          actions.push({ path, action: "conflict-upload", conflictRemoteRev: remote.rev });
          continue;
        }
        if (localMtime > remoteMtime) {
          actions.push({ path, action: "upload" });
        } else if (remoteMtime > localMtime) {
          actions.push({ path, action: "download" });
        }
      }
    }
    const priority = { upload: 0, "conflict-upload": 0, download: 1, "delete-local": 2, "delete-remote": 3 };
    actions.sort((a, b) => priority[a.action] - priority[b.action]);
    return actions;
  }
  // ─── 执行操作 ─────────────────────────────────────────────────────────
  async executeAction(action) {
    const localPath = this.remoteToLocal(action.path);
    const remotePath = this.localToRemote(localPath);
    switch (action.action) {
      case "upload":
      case "conflict-upload": {
        const file = this.vault.getFileByPath(localPath);
        if (!file) {
          console.warn("Dropbox Sync: \u4E0A\u4F20\u65F6\u6587\u4EF6\u6D88\u5931", localPath);
          return;
        }
        if (action.action === "conflict-upload" && action.conflictRemoteRev) {
          console.log("Dropbox Sync: \u51B2\u7A81\u68C0\u6D4B \u2014", localPath, "\u672C\u5730\u548C\u8FDC\u7A0B\u90FD\u5DF2\u4FEE\u6539");
          try {
            const conflictContent = await this.dropboxDownload(remotePath);
            const timestamp = (/* @__PURE__ */ new Date()).toISOString().replace(/[:.]/g, "-").slice(0, 19);
            const conflictName = this.insertSuffix(localPath, `.conflict.${timestamp}`);
            const parent = conflictName.substring(0, conflictName.lastIndexOf("/"));
            if (parent && !await this.vault.adapter.exists(parent)) {
              await this.vault.createFolder(parent);
            }
            const existing = this.vault.getFileByPath(conflictName);
            if (existing) {
              await this.vault.modifyBinary(existing, conflictContent);
            } else {
              await this.vault.createBinary(conflictName, conflictContent);
            }
            console.log("Dropbox Sync: \u51B2\u7A81\u526F\u672C\u5DF2\u4FDD\u5B58", conflictName);
          } catch (err) {
            console.error("Dropbox Sync: \u4FDD\u5B58\u51B2\u7A81\u526F\u672C\u5931\u8D25", localPath, err);
          }
        }
        const content = await this.vault.readBinary(file);
        await this.dropboxUpload(remotePath, content);
        break;
      }
      case "download": {
        const content = await this.dropboxDownload(remotePath);
        const parent = localPath.substring(0, localPath.lastIndexOf("/"));
        if (parent && !await this.vault.adapter.exists(parent)) {
          await this.vault.createFolder(parent);
        }
        const existing = this.vault.getFileByPath(localPath);
        if (existing) {
          await this.vault.modifyBinary(existing, content);
        } else {
          await this.vault.createBinary(localPath, content);
        }
        break;
      }
      case "delete-local": {
        const file = this.vault.getFileByPath(localPath);
        if (file)
          await this.vault.delete(file, true);
        break;
      }
      case "delete-remote": {
        await this.dropboxDelete(remotePath);
        break;
      }
    }
  }
  // ─── 工具函数 ─────────────────────────────────────────────────────────
  /** 在文件名中插入后缀，如 note.md → note.conflict.2024-01-01.md */
  insertSuffix(path, suffix) {
    const dot = path.lastIndexOf(".");
    if (dot === -1)
      return path + suffix;
    return path.slice(0, dot) + suffix + path.slice(dot);
  }
  // (冲突检测不再需要 hash 比对，Dropbox 的 content_hash 算法与标准 SHA-256 不兼容)
  // ─── 路径工具 ──────────────────────────────────────────────────────────
  relativePath(absolutePath) {
    if (this.options.localPrefix) {
      if (absolutePath.startsWith(this.options.localPrefix + "/")) {
        return absolutePath.substring(this.options.localPrefix.length + 1);
      }
      if (absolutePath === this.options.localPrefix)
        return "";
    }
    return absolutePath;
  }
  localToRemote(localPath) {
    const base = this.options.remoteBasePath.replace(/\/+$/, "");
    return `${base}/${localPath}`;
  }
  remoteToLocal(remotePath) {
    const prefix = this.options.localPrefix || "";
    return prefix ? `${prefix}/${remotePath}` : remotePath;
  }
  relativeRemotePath(remoteLower) {
    const base = this.options.remoteBasePath.toLowerCase().replace(/\/+$/, "");
    if (remoteLower.startsWith(base + "/")) {
      return remoteLower.substring(base.length + 1);
    }
    return remoteLower;
  }
  // ─── Token ─────────────────────────────────────────────────────────────
  async ensureValidToken() {
    if (isTokenExpired(this.token)) {
      console.log("Dropbox Sync: token \u8FC7\u671F\uFF0C\u5237\u65B0\u2026");
      this.token = await refreshToken(this.options.clientId, this.token);
      console.log("Dropbox Sync: token \u5237\u65B0\u6210\u529F");
    }
  }
  // ─── Dropbox API ───────────────────────────────────────────────────────
  async dropboxListFolder(path, recursive = true) {
    const body = JSON.stringify({ path, recursive, include_media_info: false, include_deleted: false, include_has_explicit_shared_members: false });
    const response = await this.apiCall("https://api.dropboxapi.com/2/files/list_folder", body);
    return JSON.parse(response.text);
  }
  async dropboxListFolderContinue(cursor) {
    const body = JSON.stringify({ cursor });
    const response = await this.apiCall("https://api.dropboxapi.com/2/files/list_folder/continue", body);
    return JSON.parse(response.text);
  }
  async dropboxUpload(remotePath, content) {
    const headers = {
      "Content-Type": "application/octet-stream",
      "Dropbox-API-Arg": JSON.stringify({ path: remotePath, mode: "overwrite", autorename: false, mute: false })
    };
    await this.apiCallBinary("https://content.dropboxapi.com/2/files/upload", content, headers);
  }
  async dropboxDownload(remotePath) {
    const headers = {
      "Dropbox-API-Arg": JSON.stringify({ path: remotePath })
    };
    const response = await this.apiCallBinary("https://content.dropboxapi.com/2/files/download", null, headers);
    return response.arrayBuffer();
  }
  async dropboxDelete(remotePath) {
    const body = JSON.stringify({ path: remotePath });
    await this.apiCall("https://api.dropboxapi.com/2/files/delete_v2", body);
  }
  async createRemoteFolder() {
    const body = JSON.stringify({ path: this.options.remoteBasePath, autorename: false });
    try {
      await this.apiCall("https://api.dropboxapi.com/2/files/create_folder_v2", body);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      if (!msg.includes("409"))
        throw err;
    }
  }
  // ─── HTTP ──────────────────────────────────────────────────────────────
  async apiCall(url, body) {
    console.log("Dropbox Sync: API", url);
    const response = await (0, import_obsidian2.requestUrl)({
      url,
      method: "POST",
      headers: { "Authorization": `Bearer ${this.token.access_token}`, "Content-Type": "application/json" },
      body,
      throw: false
    });
    if (response.status >= 400) {
      throw new Error(`Dropbox API \u9519\u8BEF (${response.status}): ${response.text}`);
    }
    return { status: response.status, text: response.text };
  }
  async apiCallBinary(url, body, extraHeaders) {
    const headers = { "Authorization": `Bearer ${this.token.access_token}`, ...extraHeaders };
    const response = await (0, import_obsidian2.requestUrl)({
      url,
      method: "POST",
      headers,
      body: body != null ? body : void 0,
      throw: false
    });
    if (response.status >= 400) {
      throw new Error(`Dropbox API \u9519\u8BEF (${response.status}): ${response.text}`);
    }
    return { arrayBuffer: () => Promise.resolve(response.arrayBuffer) };
  }
};

// src/settings.ts
var import_obsidian3 = require("obsidian");
var DEFAULT_SETTINGS = {
  clientId: "",
  dropboxToken: null,
  syncDirection: "upload",
  remotePath: "/Apps/ObsidianSync",
  localPrefix: "",
  maxFileSize: 50 * 1024 * 1024,
  // 50 MB
  syncOnSave: true,
  lastSyncAt: 0,
  remoteCursor: null,
  incrementalCount: 0
};
var SettingsTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    try {
      containerEl.createEl("h2", { text: "Dropbox \u540C\u6B65" });
      containerEl.createEl("h3", { text: "\u6388\u6743" });
      const token = loadToken(this.plugin.settings.dropboxToken);
      const isAuthed = isTokenValid(token);
      const statusEl = containerEl.createEl("div", {
        cls: `dropbox-sync-auth-status ${isAuthed ? "authorized" : "unauthorized"}`
      });
      statusEl.textContent = isAuthed ? "\u2705 \u5DF2\u6388\u6743 Dropbox" : "\u274C \u672A\u6388\u6743 \u2014 \u8BF7\u5728\u4E0B\u65B9\u586B\u5199 App Key \u5E76\u6388\u6743";
      new import_obsidian3.Setting(containerEl).setName("Dropbox App Key").setDesc(
        "\u5728 https://www.dropbox.com/developers/apps \u521B\u5EFA\u5E94\u7528\uFF0C\u590D\u5236 App Key \u7C98\u8D34\u81F3\u6B64"
      ).addText(
        (text) => text.setPlaceholder("\u4F60\u7684 Dropbox App Key").setValue(this.plugin.settings.clientId).onChange(async (value) => {
          this.plugin.settings.clientId = value;
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian3.Setting(containerEl).addButton((btn) => {
        btn.setButtonText(isAuthed ? "\u91CD\u65B0\u6388\u6743" : "\u6388\u6743 Dropbox").setCta().onClick(async () => {
          if (!this.plugin.settings.clientId) {
            new import_obsidian3.Notice("\u8BF7\u5148\u586B\u5199 Dropbox App Key");
            return;
          }
          try {
            btn.setDisabled(true);
            btn.setButtonText("\u6388\u6743\u4E2D\u2026");
            await this.plugin.authorizeDropbox();
            new import_obsidian3.Notice("Dropbox \u6388\u6743\u6210\u529F\uFF01");
            this.display();
          } catch (err) {
            const msg = err instanceof Error ? err.message : String(err);
            new import_obsidian3.Notice(`\u6388\u6743\u5931\u8D25\uFF1A${msg}`, 8e3);
          } finally {
            btn.setDisabled(false);
            this.display();
          }
        });
      });
      if (isAuthed) {
        new import_obsidian3.Setting(containerEl).addButton((btn) => {
          btn.setButtonText("\u64A4\u9500\u6388\u6743").setWarning().onClick(async () => {
            await this.plugin.revokeDropbox();
            new import_obsidian3.Notice("\u5DF2\u64A4\u9500 Dropbox \u6388\u6743");
            this.display();
          });
        });
      }
      containerEl.createEl("h3", { text: "\u540C\u6B65\u8BBE\u7F6E" });
      new import_obsidian3.Setting(containerEl).setName("\u540C\u6B65\u65B9\u5411").setDesc("\u4E0A\u4F20\uFF1A\u5E93 \u2192 Dropbox\uFF08\u5B89\u5168\uFF09\u3002\u4E0B\u8F7D\uFF1ADropbox \u2192 \u5E93\u3002\u53CC\u5411\uFF1A\u4E24\u8FB9\u5408\u5E76\u3002").addDropdown(
        (dropdown) => dropdown.addOption("upload", "\u4E0A\u4F20\uFF08\u5E93 \u2192 Dropbox\uFF09").addOption("download", "\u4E0B\u8F7D\uFF08Dropbox \u2192 \u5E93\uFF09").addOption("two-way", "\u53CC\u5411\u540C\u6B65").setValue(this.plugin.settings.syncDirection).onChange(async (value) => {
          this.plugin.settings.syncDirection = value;
          await this.plugin.saveSettings();
          this.plugin.reloadSyncEngine();
        })
      );
      new import_obsidian3.Setting(containerEl).setName("\u8FDC\u7A0B\u8DEF\u5F84").setDesc("Dropbox \u4E0A\u7684\u540C\u6B65\u76EE\u5F55\uFF08\u4F8B\u5982 /Apps/ObsidianSync\uFF09").addText(
        (text) => text.setPlaceholder("/Apps/ObsidianSync").setValue(this.plugin.settings.remotePath).onChange(async (value) => {
          const normalized = value.startsWith("/") ? value : "/" + value;
          this.plugin.settings.remotePath = normalized || "/Apps/ObsidianSync";
          await this.plugin.saveSettings();
          this.plugin.reloadSyncEngine();
        })
      );
      new import_obsidian3.Setting(containerEl).setName("\u672C\u5730\u8DEF\u5F84\u524D\u7F00").setDesc("\u53EA\u540C\u6B65\u5E93\u7684\u67D0\u4E2A\u5B50\u6587\u4EF6\u5939\uFF08\u7559\u7A7A = \u6574\u4E2A\u5E93\uFF09\uFF0C\u4F8B\u5982\u300C\u7B14\u8BB0\u300D").addText(
        (text) => text.setPlaceholder("\u7559\u7A7A\u5219\u540C\u6B65\u6574\u4E2A\u5E93").setValue(this.plugin.settings.localPrefix).onChange(async (value) => {
          this.plugin.settings.localPrefix = value;
          await this.plugin.saveSettings();
          this.plugin.reloadSyncEngine();
        })
      );
      new import_obsidian3.Setting(containerEl).setName("\u6700\u5927\u6587\u4EF6\u5927\u5C0F").setDesc("\u8D85\u8FC7\u6B64\u5927\u5C0F\u7684\u6587\u4EF6\u5C06\u88AB\u8DF3\u8FC7\uFF080 = \u4E0D\u9650\u5236\uFF0C\u9ED8\u8BA4 50MB\uFF09").addText(
        (text) => text.setPlaceholder("52428800").setValue(String(this.plugin.settings.maxFileSize)).onChange(async (value) => {
          const num = parseInt(value, 10);
          if (!isNaN(num) && num >= 0) {
            this.plugin.settings.maxFileSize = num;
            await this.plugin.saveSettings();
          }
        })
      );
      new import_obsidian3.Setting(containerEl).setName("\u4FDD\u5B58\u65F6\u81EA\u52A8\u540C\u6B65").setDesc("\u6587\u4EF6\u5728 Obsidian \u4E2D\u4FDD\u5B58\u540E\u81EA\u52A8\u4E0A\u4F20\u5230 Dropbox").addToggle(
        (toggle) => toggle.setValue(this.plugin.settings.syncOnSave).onChange(async (value) => {
          this.plugin.settings.syncOnSave = value;
          await this.plugin.saveSettings();
        })
      );
      containerEl.createEl("h3", { text: "\u624B\u52A8\u540C\u6B65" });
      new import_obsidian3.Setting(containerEl).addButton((btn) => {
        btn.setButtonText("\u{1F504} \u7ACB\u5373\u540C\u6B65").setCta().onClick(async () => {
          if (!this.plugin.syncEngine) {
            new import_obsidian3.Notice("\u8BF7\u5148\u6388\u6743 Dropbox");
            return;
          }
          try {
            btn.setDisabled(true);
            btn.setButtonText("\u540C\u6B65\u4E2D\u2026");
            const result = await this.plugin.syncEngine.syncNow();
            this.plugin.settings.lastSyncAt = result.lastSyncAt;
            this.plugin.settings.remoteCursor = result.remoteCursor;
            this.plugin.settings.incrementalCount = result.incrementalCount;
            await this.plugin.saveSettings();
            new import_obsidian3.Notice("\u540C\u6B65\u5B8C\u6210\uFF01");
          } catch (err) {
            const msg = err instanceof Error ? err.message : String(err);
            new import_obsidian3.Notice(`\u540C\u6B65\u5931\u8D25\uFF1A${msg}`, 8e3);
          } finally {
            btn.setDisabled(false);
            btn.setButtonText("\u{1F504} \u7ACB\u5373\u540C\u6B65");
          }
        });
      });
      new import_obsidian3.Setting(containerEl).addButton((btn) => {
        btn.setButtonText("\u53D6\u6D88\u540C\u6B65").setWarning().onClick(() => {
          var _a;
          (_a = this.plugin.syncEngine) == null ? void 0 : _a.cancel();
          new import_obsidian3.Notice("\u540C\u6B65\u5DF2\u53D6\u6D88");
        });
      });
      containerEl.createEl("h3", { text: "\u8BBE\u7F6E\u6B65\u9AA4" });
      const infoEl = containerEl.createEl("div", { cls: "setting-item-description" });
      infoEl.innerHTML = `
				<ol>
					<li>\u524D\u5F80 <a href="https://www.dropbox.com/developers/apps" target="_blank">Dropbox \u5F00\u53D1\u8005\u63A7\u5236\u53F0</a></li>
					<li>\u521B\u5EFA\u65B0\u5E94\u7528 \u2192 "Scoped access" \u2192 "App folder" \u6216 "Full Dropbox"</li>
					<li>\u5728 <strong>Permissions</strong> \u6807\u7B7E\u9875\u52FE\u9009\uFF1A<code>files.metadata.read</code>\u3001<code>files.content.read</code>\u3001<code>files.content.write</code></li>
					<li>\u5728 <strong>OAuth 2</strong> \u4E2D\u8BBE\u7F6E\u91CD\u5B9A\u5411 URI\uFF1A<code>http://127.0.0.1:54219/</code></li>
					<li>\u590D\u5236 <strong>App Key</strong> \u7C98\u8D34\u5230\u4E0A\u65B9\u8F93\u5165\u6846</li>
					<li>\u70B9\u51FB "\u6388\u6743 Dropbox" \u2192 \u5728\u6D4F\u89C8\u5668\u4E2D\u5B8C\u6210\u6388\u6743</li>
					<li>\u6388\u6743\u540E\u6D4F\u89C8\u5668\u8DF3\u8F6C\u5230 <code>http://127.0.0.1:54219/</code>\uFF08\u663E\u793A\u65E0\u6CD5\u8BBF\u95EE \u2014 \u6B63\u5E38\uFF09</li>
					<li>\u590D\u5236\u6D4F\u89C8\u5668\u5730\u5740\u680F\u7684\u5B8C\u6574\u7F51\u5740 \u2192 \u56DE\u5230 Obsidian \u2192 \u7C98\u8D34\u5230\u5F39\u51FA\u7684\u5BF9\u8BDD\u6846</li>
				</ol>
				<p>\u6388\u6743\u540E\uFF0C\u4F60\u7684\u5E93\u4F1A\u81EA\u52A8\u540C\u6B65\u5230 Dropbox \u7684 <code>${this.plugin.settings.remotePath}/</code> \u76EE\u5F55\u3002</p>
			`;
    } catch (err) {
      console.error("Dropbox Sync: display error", err);
    }
  }
};

// src/main.ts
var DropboxSyncPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.syncEngine = null;
    this.statusBarItem = null;
    this.statusInterval = null;
    this.debouncedUpload = this.debounce(async (file) => {
      if (!this.syncEngine)
        return;
      await this.syncEngine.uploadFile(file);
      this.refreshStatusBar();
    }, 2e3);
  }
  // ─── Lifecycle ───────────────────────────────────────────────────────────
  async onload() {
    await this.loadSettings();
    this.statusBarItem = this.addStatusBarItem();
    this.statusBarItem.addClass("dropbox-sync-status-bar");
    this.updateStatusBar("idle");
    this.addSettingTab(new SettingsTab(this.app, this));
    this.registerCommands();
    this.registerEventHooks();
    this.initSyncEngine();
    this.statusInterval = window.setInterval(() => this.refreshStatusBar(), 5e3);
  }
  onunload() {
    var _a;
    (_a = this.syncEngine) == null ? void 0 : _a.cancel();
    if (this.statusInterval !== null) {
      clearInterval(this.statusInterval);
    }
  }
  // ─── Sync Engine ─────────────────────────────────────────────────────────
  initSyncEngine() {
    var _a, _b, _c;
    const token = loadToken(this.settings.dropboxToken);
    if (!isTokenValid(token)) {
      this.syncEngine = null;
      return;
    }
    this.syncEngine = new SyncEngine(this.app.vault, token, {
      direction: this.settings.syncDirection,
      remoteBasePath: this.settings.remotePath,
      localPrefix: this.settings.localPrefix,
      maxFileSize: this.settings.maxFileSize,
      clientId: this.settings.clientId,
      lastSyncAt: (_a = this.settings.lastSyncAt) != null ? _a : 0,
      remoteCursor: (_b = this.settings.remoteCursor) != null ? _b : null,
      incrementalCount: (_c = this.settings.incrementalCount) != null ? _c : 0
    });
  }
  /**
   * Re-create the sync engine (e.g. after auth or settings change).
   */
  reloadSyncEngine() {
    var _a;
    (_a = this.syncEngine) == null ? void 0 : _a.cancel();
    this.initSyncEngine();
  }
  // ─── OAuth ───────────────────────────────────────────────────────────────
  /**
   * Start Dropbox authorization flow.
   */
  async authorizeDropbox() {
    const config = {
      clientId: this.settings.clientId
    };
    try {
      const token = await authorize(config);
      Object.assign(this.settings, saveToken(token));
      await this.saveSettings();
      this.reloadSyncEngine();
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      throw new Error(`Authorization failed: ${msg}`);
    }
  }
  /**
   * Revoke Dropbox authorization.
   */
  async revokeDropbox() {
    var _a;
    Object.assign(this.settings, clearToken());
    await this.saveSettings();
    (_a = this.syncEngine) == null ? void 0 : _a.cancel();
    this.syncEngine = null;
  }
  // ─── Commands ────────────────────────────────────────────────────────────
  registerCommands() {
    this.addCommand({
      id: "sync-now",
      name: "\u7ACB\u5373\u5168\u91CF\u540C\u6B65",
      callback: async () => {
        if (!this.syncEngine) {
          new import_obsidian4.Notice("Dropbox \u540C\u6B65\uFF1A\u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u6388\u6743");
          return;
        }
        try {
          const result = await this.syncEngine.syncNow();
          this.settings.lastSyncAt = result.lastSyncAt;
          this.settings.remoteCursor = result.remoteCursor;
          this.settings.incrementalCount = result.incrementalCount;
          await this.saveSettings();
          console.log("Dropbox Sync: \u540C\u6B65\u72B6\u6001\u5DF2\u4FDD\u5B58", {
            lastSyncAt: new Date(result.lastSyncAt).toISOString(),
            fullScanDone: result.fullScanDone,
            incrementalCount: result.incrementalCount
          });
          this.refreshStatusBar();
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          new import_obsidian4.Notice(`Dropbox \u540C\u6B65\u9519\u8BEF\uFF1A${msg}`, 8e3);
        }
      }
    });
    this.addCommand({
      id: "cancel-sync",
      name: "\u53D6\u6D88\u540C\u6B65",
      callback: () => {
        var _a;
        (_a = this.syncEngine) == null ? void 0 : _a.cancel();
        new import_obsidian4.Notice("Dropbox \u540C\u6B65\u5DF2\u53D6\u6D88");
      }
    });
  }
  // ─── Events ──────────────────────────────────────────────────────────────
  registerEventHooks() {
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (!this.syncEngine || !this.settings.syncOnSave)
          return;
        if (!this.syncEngine.shouldSync(file))
          return;
        this.debouncedUpload(file);
      })
    );
    this.registerEvent(
      this.app.vault.on("create", (file) => {
        if (!this.syncEngine || !this.settings.syncOnSave)
          return;
        if (!this.syncEngine.shouldSync(file))
          return;
        this.debouncedUpload(file);
      })
    );
  }
  // ─── Status Bar ──────────────────────────────────────────────────────────
  refreshStatusBar() {
    if (!this.statusBarItem)
      return;
    if (!this.syncEngine) {
      this.updateStatusBar("unauthorized");
      return;
    }
    const status = this.syncEngine.getStatus();
    if (status.running) {
      this.updateStatusBar("syncing", status);
    } else if (status.lastError) {
      this.updateStatusBar("error", status);
    } else if (status.lastSyncAt) {
      this.updateStatusBar("synced", status);
    } else {
      this.updateStatusBar("idle");
    }
  }
  updateStatusBar(state, status) {
    var _a, _b;
    if (!this.statusBarItem)
      return;
    this.statusBarItem.empty();
    this.statusBarItem.className = `dropbox-sync-status-bar ${state}`;
    switch (state) {
      case "unauthorized":
        this.statusBarItem.setText("\u2601\uFE0F Dropbox \u2014 \u672A\u6388\u6743");
        break;
      case "syncing":
        this.statusBarItem.setText(
          `\u2601\uFE0F \u540C\u6B65\u4E2D\u2026 ${(_a = status == null ? void 0 : status.progress.completed) != null ? _a : 0}/${(_b = status == null ? void 0 : status.progress.total) != null ? _b : 0}`
        );
        break;
      case "synced": {
        const last = (status == null ? void 0 : status.lastSyncAt) ? new Date(status.lastSyncAt).toLocaleTimeString() : "?";
        this.statusBarItem.setText(`\u2601\uFE0F \u5DF2\u540C\u6B65 ${last}`);
        break;
      }
      case "error":
        this.statusBarItem.setText("\u2601\uFE0F \u540C\u6B65\u51FA\u9519");
        break;
      default:
        this.statusBarItem.setText("\u2601\uFE0F Dropbox");
        break;
    }
  }
  // ─── Settings ────────────────────────────────────────────────────────────
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data);
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // ─── Utility ─────────────────────────────────────────────────────────────
  debounce(fn, delay) {
    let timer = null;
    return (...args) => {
      if (timer !== null)
        clearTimeout(timer);
      timer = window.setTimeout(() => {
        fn(...args);
        timer = null;
      }, delay);
    };
  }
};
